const waterQuestions=[
{scene:'河流里主流很急，桥墩后方形成明显缓流带，边缘还有小鱼活动。你先试哪里？',opts:['正冲主流中心','桥墩后缓流与主流交界','随便找最深处'],ok:1,why:'先验证速度交界：鱼可能用较低游泳成本接触被主流带来的食物。'},
{scene:'水库退水明显，原来浅湾裸露，湾口外侧还有连续坡坎。你最该先验证？',opts:['继续守已经很浅的湾底','湾口外的深浅交界','只换更香的饵'],ok:1,why:'环境已经改变空间条件，先换位置/钓层比同时大改饵更有信息量。'},
{scene:'清水、晴天、岸边人影明显，近岸结构不错但没有鱼讯。第一步更合理的是？',opts:['减少惊扰并拉开距离','不断加大拟饵动作','马上判定这里没鱼'],ok:0,why:'清水条件下先降低惊扰、优化距离和自然呈现，再评价位置。'}
];
const openGames={
  monad:{title:'MonadFish',icon:'🐠',url:'https://kaimiewl.github.io/fishing-game/',license:'MIT',repo:'KaimiEwl/fishing-game',note:'移动端友好的浏览器钓鱼游戏，包含地图、鱼种、升级与任务。'},
  gofish:{title:'Go Fishing',icon:'🚤',url:'https://fadyjohn10.github.io/Go-Fishing/',license:'MIT',repo:'FadyJohn10/Go-Fishing',note:'开船 + 抛竿的浏览器小游戏，支持单人/双人键盘玩法；电脑体验更好。'},
  phaserfish:{title:'Phaser Fish Game',icon:'🐟',url:'https://everybodycodes.github.io/Phaser-Fish-Game/',license:'GPL-3.0',repo:'EverybodyCodes/Phaser-Fish-Game',note:'Phaser 开源水下小游戏；偏休闲娱乐，不代表真实钓鱼逻辑。'}
};
function games(){if(S.gameScreen==='classic')return classicGame();if(S.gameScreen==='reaction')return reactionGame();if(S.gameScreen==='water')return waterGame();if(openGames[S.gameScreen])return externalGame(S.gameScreen);S.gameScreen='hub';shell(`<div class="hero"><span class="eyebrow">小游戏中心</span><h1>想学就学，想玩就直接玩。</h1><div class="lead">本站小游戏和开源钓鱼游戏都直接在当前网页内打开，不再放 4399 洽谈或候选内容。</div></div><div class="gamegrid"><button class="gamecard" data-game="classic"><span class="gicon">🎣</span><b>经典抛竿小游戏</b><small>保留早期虚拟钓鱼玩法：选水面、抛竿、咬口、收线。</small><span class="badge">本站游戏</span></button><button class="gamecard" data-game="reaction"><span class="gicon">⚡</span><b>提竿反应训练</b><small>等鱼口出现再点，测反应时间；抢跑也会被记录。</small><span class="badge">30秒一局</span></button><button class="gamecard" data-game="water"><span class="gicon">🌊</span><b>读水找点挑战</b><small>用真实钓鱼逻辑做快速场景题，答完立即解释。</small><span class="badge">边玩边学</span></button><button class="gamecard" data-jumpplay="1"><span class="gicon">🕵️</span><b>现实谜题挑战</b><small>先押判断，再去现实水边让结果揭晓。</small><span class="badge">Reality-first</span></button></div><section class="card"><span class="eyebrow">开源钓鱼游戏 · 网页内嵌</span><div class="title">换一种玩法，也不用离开本站。</div><div class="gamegrid">${Object.entries(openGames).map(([id,g])=>`<button class="gamecard" data-game="${id}"><span class="gicon">${g.icon}</span><b>${g.title}</b><small>${g.note}</small><span class="badge">${g.license} · 开源</span></button>`).join('')}</div><div class="legalnote" style="margin-top:10px">这些游戏通过其公开 GitHub Pages 在本站 iframe 中显示，版权和许可证归原项目；我们不复制或冒充原作者内容。若源项目下线，内嵌也会失效。</div></section>`,'小游戏中心');app.querySelectorAll('[data-game]').forEach(b=>b.onclick=()=>{S.gameScreen=b.dataset.game;render()});document.querySelector('[data-jumpplay]')?.addEventListener('click',()=>{S.tab='play';S.screen='root';S.mode='mystery';save.tab='play';persist();render()})}
function gameBack(){S.gameScreen='hub';if(S.reactionTimer){clearTimeout(S.reactionTimer);S.reactionTimer=null}render()}
function externalGame(id){let g=openGames[id];shell(`<section class="card deep"><span class="eyebrow" style="color:#ffdc91">开源游戏</span><div class="title">${g.icon} ${g.title}</div><div class="sub">${g.note}</div><div class="pillrow"><span class="pill on" style="color:white">${g.license}</span><span class="pill on" style="color:white">${g.repo}</span></div><button id="gameBack" class="secondary" style="margin-top:10px">← 游戏中心</button></section><iframe class="gameframe external" src="${g.url}" title="${g.title}" allow="fullscreen; autoplay; gamepad" referrerpolicy="no-referrer" loading="eager"></iframe><div class="legalnote">游戏在当前页面内运行，但来自独立开源项目。若源站设置禁止 iframe，浏览器可能拒绝显示；本站不会绕过其安全策略。</div>`,'小游戏中心');document.querySelector('#gameBack').onclick=gameBack}
function classicGame(){shell(`<section class="card deep"><div class="title">🎣 经典抛竿小游戏</div><div class="sub">这是早期虚拟钓鱼玩法，保留为“纯娱乐”入口；它和现实任务体系并存，不再冒充现实鱼情。</div><button id="gameBack" class="secondary" style="margin-top:10px">← 游戏中心</button></section><iframe class="gameframe" src="/fish/game-lab/" title="经典抛竿小游戏" allow="fullscreen" loading="eager"></iframe>`,'小游戏中心');document.querySelector('#gameBack').onclick=gameBack}
function reactionGame(){shell(`<section class="card"><span class="eyebrow">提竿反应训练</span><div class="title">别抢跑。看到“有口！”再点。</div><div id="reactionPad" class="reactionPad"><div><div style="font-size:54px">🎣</div><b id="reactionText">准备好了吗？</b><div class="sub" style="color:#d4e4e1;margin-top:6px">模拟突然鱼口，只测反应，不代表真实提竿时机。</div><button id="reactionStart" class="primary gold">开始等待</button></div></div><button id="gameBack" class="secondary" style="width:100%;margin-top:10px">← 游戏中心</button></section>`,'小游戏中心');document.querySelector('#gameBack').onclick=gameBack;document.querySelector('#reactionStart').onclick=startReaction}
function startReaction(){let pad=document.querySelector('#reactionPad');S.reactionReady=false;document.querySelector('#reactionText').textContent='等鱼口…';document.querySelector('#reactionStart').style.display='none';pad.onclick=()=>{if(!S.reactionReady){if(S.reactionTimer)clearTimeout(S.reactionTimer);S.reactionTimer=null;pad.onclick=null;document.querySelector('#reactionText').textContent='抢跑了 😂';setTimeout(()=>reactionGame(),850)}};S.reactionTimer=setTimeout(()=>{S.reactionReady=true;S.reactionStart=performance.now();pad.innerHTML='<button id="hitNow" class="reactionTarget">有口！</button>';document.querySelector('#hitNow').onclick=e=>{e.stopPropagation();let ms=Math.round(performance.now()-S.reactionStart);gainXP(ms<450?3:1,`提竿反应 ${ms}ms`);pad.onclick=null;pad.innerHTML=`<div><div style="font-size:54px">${ms<300?'⚡':ms<500?'🎯':'🐢'}</div><b>${ms} ms</b><div class="sub" style="color:#d4e4e1;margin-top:6px">${ms<300?'反应很快，但现实里仍要看鱼种和信号。':ms<500?'不错。重点仍是识别“有效鱼口”，不是单纯拼手速。':'慢一点也没关系，先把假信号和真入口分清。'}</div><button id="again" class="primary gold">再来一次</button></div>`;document.querySelector('#again').onclick=reactionGame}},800+Math.random()*1900)}
function waterGame(){let q=waterQuestions[S.waterQ%waterQuestions.length];shell(`<section class="card green"><span class="eyebrow">读水找点 · ${S.waterQ%waterQuestions.length+1}/3</span><div class="title">${q.scene}</div><div id="waterOpts">${q.opts.map((o,i)=>`<button class="waterChoice" data-wopt="${i}">${i+1}. ${o}</button>`).join('')}</div><div id="waterExplain" class="sub" style="margin-top:12px">先选一个最值得验证的起点。</div><button id="nextWater" class="primary" style="display:none">下一题</button><button id="gameBack" class="secondary" style="width:100%;margin-top:9px">← 游戏中心</button></section>`,'小游戏中心');document.querySelector('#gameBack').onclick=gameBack;document.querySelectorAll('[data-wopt]').forEach(b=>b.onclick=()=>{let i=Number(b.dataset.wopt);document.querySelectorAll('[data-wopt]').forEach(x=>x.disabled=true);b.classList.add(i===q.ok?'good':'bad');if(i!==q.ok)document.querySelector(`[data-wopt="${q.ok}"]`).classList.add('good');document.querySelector('#waterExplain').innerHTML=`<b>${i===q.ok?'✅ 判断不错':'↪️ 更值得先试另一个方向'}</b><br>${q.why}`;if(i===q.ok)gainXP(2,'读水找点判断');let n=document.querySelector('#nextWater');n.style.display='block';n.textContent=(S.waterQ%waterQuestions.length===2)?'完成挑战':'下一题';n.onclick=()=>{if(S.waterQ%waterQuestions.length===2){S.waterQ=0;save.lastResult='完成了一轮读水找点挑战';persist();games()}else{S.waterQ++;waterGame()}}})}