(()=>{
const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d');
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let W=innerWidth,H=innerHeight,DPR=Math.min(2,devicePixelRatio||1),t=0,last=0;
let state='intro', zone=null, playerX=.18, targetPlayerX=.18, castTarget=null,bobber=null,lineProgress=0,biteAt=0,biteDeadline=0,hookedFish=null,reeling=false,tension=.32,fishHP=1, fightTime=0, splash=[], ripples=[], particles=[], fishShadows=[], dex=new Set(JSON.parse(localStorage.getItem('fishAdventureDex')||'[]')),xp=+(localStorage.getItem('fishAdventureXp')||0),streak=0,selectedSpot=null;
const zones={reed:{x:.24,name:'芦苇边',waterX:.33,waterY:.61,color:'#265c55'},drop:{x:.5,name:'深浅坎',waterX:.55,waterY:.64,color:'#174f66'},flow:{x:.76,name:'缓流口',waterX:.75,waterY:.57,color:'#237485'}};
const species=[
 {name:'鲫鱼',icon:'🐟',rarity:1,desc:'喜欢在近岸缓流和结构边活动，是非常适合新手认识鱼口节奏的对象鱼。',zones:['reed','flow']},
 {name:'黄颡鱼',icon:'🐠',rarity:2,desc:'偏底层、喜欢结构与遮蔽。夜晚或浑水环境里存在感往往更强。',zones:['reed','drop']},
 {name:'鲤鱼',icon:'🐡',rarity:3,desc:'底层力量型选手。中鱼后更需要稳定张力和耐心，而不是一味暴力收线。',zones:['drop','flow']},
 {name:'翘嘴',icon:'🐟',rarity:3,desc:'会追逐小鱼和活动猎物，看到水面追逐、炸水时尤其值得关注。',zones:['flow']},
 {name:'鳜鱼',icon:'🐲',rarity:4,desc:'典型伏击型掠食者，结构、障碍和水流交界往往比“神饵”更重要。',zones:['drop','reed']},
 {name:'神秘银影',icon:'✨🐟',rarity:5,desc:'极少出现的水下银影。它提醒你：探索未知本身就是钓鱼最迷人的奖励。',zones:['drop','flow']}
];
function resize(){W=innerWidth;H=innerHeight;canvas.width=W*DPR;canvas.height=H*DPR;canvas.style.width=W+'px';canvas.style.height=H+'px';ctx.setTransform(DPR,0,0,DPR,0,0)}addEventListener('resize',resize);resize();
function lerp(a,b,k){return a+(b-a)*k}function rand(a,b){return a+Math.random()*(b-a)}function clamp(v,a,b){return Math.max(a,Math.min(b,v))}
function toast(s){let x=$('#toast');x.textContent=s;x.classList.add('show');clearTimeout(x._t);x._t=setTimeout(()=>x.classList.remove('show'),1400)}
function guide(title,text,ms=3600){$('#guideTitle').textContent=title;$('#guideText').textContent=text;$('#guide').classList.remove('hidden');clearTimeout(guide._t);guide._t=setTimeout(()=>$('#guide').classList.add('hidden'),ms)}
function beep(freq=440,d=.06,type='sine',gain=.035){try{const ac=beep.ac||(beep.ac=new(window.AudioContext||window.webkitAudioContext)());const o=ac.createOscillator(),g=ac.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(gain,ac.currentTime);g.gain.exponentialRampToValueAtTime(.001,ac.currentTime+d);o.connect(g).connect(ac.destination);o.start();o.stop(ac.currentTime+d)}catch{}}
function mission(a,b){$('#mission').textContent=a;$('#subMission').textContent=b||''}
function updateHud(){let lv=1+Math.floor(xp/180);$('#lv').textContent='LV.'+lv;$('#dex').textContent=dex.size+'/12';$('#streak').textContent=streak}
function waterY(x){return H*.54+Math.sin(x*.012+t*.0012)*4}
function addRipple(x,y,color='rgba(230,255,255,.45)'){ripples.push({x,y,r:2,a:.75,color})}
function addSplash(x,y,n=14){for(let i=0;i<n;i++)particles.push({x,y,vx:rand(-1.7,1.7),vy:rand(-4,-1.5),life:1,s:rand(1,3)});addRipple(x,y)}
function spawnFishShadows(){fishShadows=[];for(let i=0;i<7;i++)fishShadows.push({x:rand(W*.28,W*.9),y:rand(H*.58,H*.82),vx:rand(-.22,.22),phase:rand(0,6.28),size:rand(16,32),alpha:rand(.06,.17)})}
spawnFishShadows();
function drawSky(){let g=ctx.createLinearGradient(0,0,0,H*.56);g.addColorStop(0,'#7ed7e8');g.addColorStop(.7,'#b7e7df');g.addColorStop(1,'#e8e2bb');ctx.fillStyle=g;ctx.fillRect(0,0,W,H*.58);
 ctx.fillStyle='rgba(255,245,196,.75)';ctx.beginPath();ctx.arc(W*.81,H*.15,Math.min(W,H)*.055,0,Math.PI*2);ctx.fill();
 for(let i=0;i<4;i++){let x=(i*.29*W+(t*.006*(i%2?1:-1)))%(W+180)-90,y=H*(.10+.045*(i%3));ctx.fillStyle='rgba(255,255,255,.42)';ctx.beginPath();ctx.ellipse(x,y,58,18,0,0,6.28);ctx.ellipse(x+38,y+2,42,14,0,0,6.28);ctx.fill()}}
function drawHills(){ctx.fillStyle='#527b62';ctx.beginPath();ctx.moveTo(0,H*.43);for(let x=0;x<=W;x+=60)ctx.lineTo(x,H*.40-Math.sin(x*.009)*34-Math.sin(x*.021)*15);ctx.lineTo(W,H*.59);ctx.lineTo(0,H*.59);ctx.fill();ctx.fillStyle='#3d674f';ctx.beginPath();ctx.moveTo(0,H*.49);for(let x=0;x<=W;x+=48)ctx.lineTo(x,H*.47-Math.sin(x*.013+1.2)*24);ctx.lineTo(W,H*.59);ctx.lineTo(0,H*.59);ctx.fill()}
function drawWater(){let g=ctx.createLinearGradient(0,H*.5,0,H);g.addColorStop(0,'#58b7b4');g.addColorStop(.35,'#298e96');g.addColorStop(1,'#0a566b');ctx.fillStyle=g;ctx.fillRect(0,H*.52,W,H*.48);
 ctx.lineWidth=1;for(let i=0;i<18;i++){let y=H*.55+i*(H*.45/18),off=Math.sin(t*.0013+i)*18;ctx.strokeStyle=`rgba(220,250,241,${.08+i*.002})`;ctx.beginPath();for(let x=-30;x<W+30;x+=38){ctx.moveTo(x+off,y);ctx.quadraticCurveTo(x+11+off,y-3,x+25+off,y)}ctx.stroke()}
 ctx.strokeStyle='rgba(157,245,231,.14)';ctx.lineWidth=2;for(let i=0;i<4;i++){let y=H*(.58+i*.035);ctx.beginPath();ctx.moveTo(W*.66,y);ctx.bezierCurveTo(W*.72,y-10,W*.79,y+9,W*.9,y-4);ctx.stroke()}
}
function drawBank(){ctx.fillStyle='#8d8b5f';ctx.beginPath();ctx.moveTo(0,H*.5);ctx.quadraticCurveTo(W*.18,H*.54,W*.28,H*.65);ctx.quadraticCurveTo(W*.18,H*.73,0,H*.76);ctx.closePath();ctx.fill();ctx.fillStyle='#566f48';ctx.beginPath();ctx.moveTo(0,H*.48);ctx.quadraticCurveTo(W*.16,H*.51,W*.27,H*.61);ctx.lineTo(W*.22,H*.66);ctx.quadraticCurveTo(W*.13,H*.61,0,H*.63);ctx.closePath();ctx.fill();
 for(let i=0;i<14;i++){let x=W*(.17+.008*i),y=H*(.58+.007*Math.sin(i));ctx.strokeStyle=i%2?'#466d3f':'#6e8b45';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(x,y+22);ctx.quadraticCurveTo(x+Math.sin(t*.002+i)*5,y-15,x+rand(-2,2),y-34-rand(0,12));ctx.stroke()}}
function drawFishShadows(dt){fishShadows.forEach(f=>{f.x+=f.vx*dt;f.phase+=dt*.001;if(f.x<W*.28||f.x>W*.94)f.vx*=-1;ctx.save();ctx.translate(f.x,f.y+Math.sin(f.phase)*4);ctx.rotate(f.vx*.4);ctx.fillStyle=`rgba(3,35,44,${f.alpha})`;ctx.beginPath();ctx.ellipse(0,0,f.size,5,0,0,6.28);ctx.moveTo(-f.size,0);ctx.lineTo(-f.size-10,-7);ctx.lineTo(-f.size-10,7);ctx.closePath();ctx.fill();ctx.restore()})}
function drawHotspots(){if(state!=='explore'&&state!=='aim')return;Object.entries(zones).forEach(([k,z],i)=>{let x=z.x*W,y=H*.60;let pulse=8+Math.sin(t*.004+i)*4;ctx.strokeStyle=zone===k?'rgba(122,245,207,.95)':'rgba(255,231,145,.7)';ctx.lineWidth=2;ctx.beginPath();ctx.arc(x,y,pulse,0,6.28);ctx.stroke();ctx.fillStyle=zone===k?'rgba(122,245,207,.25)':'rgba(255,231,145,.18)';ctx.beginPath();ctx.arc(x,y,pulse*1.8,0,6.28);ctx.fill()})}
function drawPlayer(){let x=playerX*W,y=H*.57;ctx.save();ctx.translate(x,y);ctx.fillStyle='#123d46';ctx.fillRect(-5,-2,10,25);ctx.fillStyle='#f2c38f';ctx.beginPath();ctx.arc(0,-9,7,0,6.28);ctx.fill();ctx.fillStyle='#ffcb58';ctx.fillRect(-10,-16,20,5);ctx.fillStyle='#0d3140';ctx.beginPath();ctx.moveTo(-4,23);ctx.lineTo(-9,37);ctx.lineTo(-4,38);ctx.lineTo(1,24);ctx.lineTo(6,38);ctx.lineTo(11,37);ctx.lineTo(5,22);ctx.fill();ctx.strokeStyle='#34271f';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(5,4);ctx.lineTo(27,-19);ctx.stroke();ctx.restore()}
function drawCast(){if(!castTarget)return;let px=playerX*W+27,py=H*.57-19;let progress=clamp(lineProgress,0,1);let tx=castTarget.x,ty=castTarget.y;let bx=lerp(px,tx,progress),by=lerp(py,ty,progress)-Math.sin(progress*Math.PI)*H*.18;ctx.strokeStyle='rgba(246,250,236,.7)';ctx.lineWidth=1.2;ctx.beginPath();ctx.moveTo(px,py);ctx.quadraticCurveTo((px+tx)/2,Math.min(py,ty)-H*.22,bx,by);ctx.stroke();if(bobber){ctx.strokeStyle='rgba(245,250,240,.58)';ctx.beginPath();ctx.moveTo(px,py);ctx.lineTo(bobber.x,bobber.y);ctx.stroke();ctx.fillStyle='#fff';ctx.fillRect(bobber.x-2,bobber.y-8,4,11);ctx.fillStyle='#ff654e';ctx.fillRect(bobber.x-2,bobber.y-8,4,5);if(state==='waiting')addRippleMaybe(bobber.x,bobber.y+4)}}
let rippleTick=0;function addRippleMaybe(x,y){if(t-rippleTick>1100){addRipple(x,y,'rgba(255,255,255,.28)');rippleTick=t}}
function drawRipples(dt){for(let i=ripples.length-1;i>=0;i--){let r=ripples[i];r.r+=dt*.018;r.a-=dt*.00045;if(r.a<=0){ripples.splice(i,1);continue}ctx.strokeStyle=r.color.replace(/\.[0-9]+\)$/,r.a+')');ctx.lineWidth=1.3;ctx.beginPath();ctx.ellipse(r.x,r.y,r.r*1.7,r.r*.55,0,0,6.28);ctx.stroke()}}
function drawParticles(dt){for(let i=particles.length-1;i>=0;i--){let p=particles[i];p.x+=p.vx*dt*.06;p.y+=p.vy*dt*.06;p.vy+=dt*.008;p.life-=dt*.0016;if(p.life<=0){particles.splice(i,1);continue}ctx.fillStyle=`rgba(225,252,244,${p.life})`;ctx.beginPath();ctx.arc(p.x,p.y,p.s,0,6.28);ctx.fill()}}
function drawFishFight(){if(state!=='fight'||!hookedFish)return;let baseX=W*.65,baseY=H*.66;let amp=Math.min(W*.16,120);let fx=baseX+Math.sin(fightTime*.005)*amp,fy=baseY+Math.sin(fightTime*.008+1)*H*.06;ctx.save();ctx.translate(fx,fy);ctx.rotate(Math.sin(fightTime*.004)*.25);ctx.fillStyle='rgba(4,31,40,.35)';ctx.beginPath();ctx.ellipse(0,0,42+hookedFish.rarity*4,10,0,0,6.28);ctx.moveTo(-42,0);ctx.lineTo(-60,-13);ctx.lineTo(-60,13);ctx.fill();ctx.restore();ctx.strokeStyle='rgba(255,255,255,.55)';ctx.lineWidth=1.4;ctx.beginPath();ctx.moveTo(playerX*W+27,H*.57-19);ctx.lineTo(fx,fy);ctx.stroke();if(Math.random()<.025)addRipple(fx,fy)}
function render(ts){let dt=Math.min(32,ts-last||16);last=ts;t=ts;playerX=lerp(playerX,targetPlayerX,Math.min(1,dt*.004));drawSky();drawHills();drawWater();drawBank();drawFishShadows(dt);drawHotspots();drawPlayer();drawCast();drawFishFight();drawRipples(dt);drawParticles(dt);update(dt);requestAnimationFrame(render)}requestAnimationFrame(render);
function chooseFish(){let pool=species.filter(s=>s.zones.includes(zone));let r=Math.random();if(r<.04)return pool.sort((a,b)=>b.rarity-a.rarity)[0];if(r<.18)return pool.filter(x=>x.rarity>=3)[Math.floor(Math.random()*pool.filter(x=>x.rarity>=3).length)]||pool[0];return pool.filter(x=>x.rarity<=3)[Math.floor(Math.random()*pool.filter(x=>x.rarity<=3).length)]||pool[0]}
function startExplore(){state='explore';$('#intro').classList.remove('show');$('#zonePanel').classList.remove('hidden');$('#actionBar').classList.remove('hidden');mission('任务：选择今天的第一处钓点','三个区域都会动起来，先去看看再决定。');guide('水边向导','这次别把自己当“填表的人”。你就是屏幕里这个钓手。先选一个位置走过去。');beep(523,.09,'triangle');updateHud()}
$('#enter').onclick=startExplore;
$$('#zonePanel button').forEach(b=>b.onclick=()=>{zone=b.dataset.zone;$$('#zonePanel button').forEach(x=>x.classList.toggle('on',x===b));targetPlayerX=zones[zone].x;state='aim';selectedSpot=null;$('#cast').disabled=true;$('#cast small').textContent='点击水面选落点';mission(`任务：在${zones[zone].name}寻找落点`,'点击水面任意位置，观察鱼影后决定第一竿。');guide('已到达 '+zones[zone].name,'现在直接点水面选落点。你会看到抛竿真正飞过去。',2600);beep(330,.04,'sine')});
canvas.addEventListener('pointerdown',e=>{if(state!=='aim')return;let rect=canvas.getBoundingClientRect(),x=e.clientX-rect.left,y=e.clientY-rect.top;if(y<H*.54||x<W*.22)return;selectedSpot={x,y};castTarget={x,y};lineProgress=0;bobber=null;$('#cast').disabled=false;$('#cast small').textContent='落点已锁定';addRipple(x,y,'rgba(255,214,100,.55)');beep(600,.035,'sine');mission('落点锁定：准备抛竿','按“抛竿”，看看水下会不会有东西靠近。')});
$('#scan').onclick=()=>{fishShadows.forEach(f=>f.alpha=Math.min(.28,f.alpha+.08));toast('👀 鱼影更清楚了');guide('观察模式','鱼影只是线索，不代表一定会咬。看活动层、方向和结构。',2200);beep(740,.035)};
$('#cast').onclick=()=>{if(state!=='aim'||!selectedSpot)return;state='casting';lineProgress=0;bobber=null;$('#actionBar').classList.add('hidden');$('#zonePanel').classList.add('hidden');mission('抛竿中…','看准你的落点。');beep(260,.06,'triangle')};
function beginWaiting(){state='waiting';bobber={x:castTarget.x,y:castTarget.y};addSplash(bobber.x,bobber.y,8);lineProgress=1;let delay=rand(1800,4300);biteAt=performance.now()+delay;mission('等待咬口','盯住浮漂和鱼影，下一秒可能就会发生。');guide('保持注意','真实钓鱼最有参与感的瞬间，就是“它到底什么时候会咬？”',1900)}
function startBite(){state='bite';biteDeadline=performance.now()+1250;$('#bitePanel').classList.remove('hidden');addSplash(bobber.x,bobber.y,20);bobber.y+=8;beep(880,.08,'square',.05);setTimeout(()=>beep(660,.08,'square',.04),70);mission('咬口！现在提竿！','窗口很短。')}
$('#strike').onclick=()=>{if(state!=='bite')return;let left=biteDeadline-performance.now();$('#bitePanel').classList.add('hidden');if(left<120){miss('太晚了，鱼吐钩跑掉了。');return} if(left>1020){miss('太早了，只是试探口。');return} hookedFish=chooseFish();state='fight';fishHP=1;tension=.34;fightTime=0;$('#fightPanel').classList.remove('hidden');$('#fightName').textContent='水下黑影';$('#fightIcon').textContent=hookedFish.icon;$('#fishHp').style.width='100%';mission('中鱼！稳住张力','按住收线，鱼冲时松开。线太紧会断，太松会脱。');guide('对抗开始','不要一直按。观察张力条和鱼的冲刺节奏。',2600);beep(220,.12,'sawtooth',.04)};
function miss(msg){state='aim';castTarget=null;bobber=null;selectedSpot=null;$('#actionBar').classList.remove('hidden');$('#zonePanel').classList.remove('hidden');$('#cast').disabled=true;mission('这次没中，再试一次','换落点或留在原区继续验证。');guide('错过鱼口',msg+' 失败也应该有明确原因，而不是只扣分。',2600);streak=0;updateHud();beep(150,.12,'sawtooth')}
['pointerdown','touchstart'].forEach(ev=>$('#reel').addEventListener(ev,e=>{e.preventDefault();reeling=true;$('#reel').classList.add('active')}));['pointerup','pointercancel','pointerleave','touchend','touchcancel'].forEach(ev=>$('#reel').addEventListener(ev,e=>{e.preventDefault();reeling=false;$('#reel').classList.remove('active')}));
function update(dt){if(state==='casting'){lineProgress+=dt*.00135;if(lineProgress>=1)beginWaiting()}else if(state==='waiting'&&performance.now()>=biteAt)startBite();else if(state==='bite'&&performance.now()>biteDeadline){$('#bitePanel').classList.add('hidden');miss('鱼口结束了，你没有提竿。')}else if(state==='fight')fightUpdate(dt)}
function fightUpdate(dt){fightTime+=dt;let rush=(Math.sin(fightTime*.006)+Math.sin(fightTime*.013)*.55)>1.05;let target=rush?.82:.43;if(reeling){tension+=dt*(rush?.00038:.00024);if(tension>.24&&tension<.82)fishHP-=dt*(rush?.00007:.00013)}else{tension-=dt*(rush?.00006:.00013);tension+=dt*(target-tension)*.00012}
 tension=clamp(tension,0,1);fishHP=clamp(fishHP,0,1);$('#tensionNeedle').style.left=(tension*100)+'%';$('#fishHp').style.width=(fishHP*100)+'%';$('#tensionText').textContent=rush?'⚡ 鱼在猛冲，松手卸力！':(reeling?'正在收线…':'保持在绿色区域');if(rush&&Math.random()<.06){addSplash(W*.66+Math.sin(fightTime*.005)*90,H*.66,6);beep(120,.025,'sawtooth',.018)}if(tension>.93){fightFail('啪！线太紧断了。鱼猛冲时要松手卸力。');return}if(tension<.06&&fightTime>1800){fightFail('线松了，鱼脱钩了。保持持续但不过载的张力。');return}if(fishHP<=.01)winCatch()}
function fightFail(msg){state='aim';$('#fightPanel').classList.add('hidden');reeling=false;hookedFish=null;castTarget=bobber=selectedSpot=null;$('#actionBar').classList.remove('hidden');$('#zonePanel').classList.remove('hidden');$('#cast').disabled=true;streak=0;updateHud();mission('鱼逃走了','再试一次；你已经知道失败发生在哪一步。');guide('脱钩',msg,3000);beep(110,.18,'sawtooth',.05)}
function winCatch(){state='caught';$('#fightPanel').classList.add('hidden');addSplash(W*.55,H*.55,35);let s=hookedFish,wasNew=!dex.has(s.name);dex.add(s.name);localStorage.setItem('fishAdventureDex',JSON.stringify([...dex]));let gain=50+s.rarity*20+(wasNew?30:0);xp+=gain;localStorage.setItem('fishAdventureXp',xp);streak++;updateHud();$('#catchFish').textContent=s.icon;$('#catchName').textContent=s.name;$('#catchDesc').textContent=s.desc;$('#rarity').textContent='★'.repeat(s.rarity)+'☆'.repeat(5-s.rarity);$('#gain').textContent='+'+gain+' XP';$('.new-tag')?.classList?.toggle('hidden',!wasNew);$('#catchCard').classList.remove('hidden');mission('捕获成功！','这才是一次完整的游戏循环。');beep(523,.08,'triangle',.05);setTimeout(()=>beep(659,.08,'triangle',.05),90);setTimeout(()=>beep(784,.13,'triangle',.05),180)}
$('#continue').onclick=()=>{state='explore';$('#catchCard').classList.add('hidden');hookedFish=null;castTarget=bobber=selectedSpot=null;zone=null;$$('#zonePanel button').forEach(x=>x.classList.remove('on'));$('#zonePanel').classList.remove('hidden');$('#actionBar').classList.remove('hidden');$('#cast').disabled=true;mission('继续探索下一处水域','换一个区域，看看会遇到不同的鱼。');guide('图鉴已经记住它','下一步可以把现实里的天气、鱼讯和真实上鱼事件接进这个循环，而不是放在游戏外面。',3200)};
$('#realCatch').onclick=()=>{toast('📷 已标记：现实同步捕获');xp+=30;localStorage.setItem('fishAdventureXp',xp);updateHud();beep(920,.06,'triangle')};
$('#bag').onclick=()=>toast('🎒 背包系统下一版开放');updateHud();
})();