/* Engineer Adaptive OS V11 · Today UX + Pomodoro */
(function(){
'use strict';
const byId=id=>document.getElementById(id),page=byId('page-today');if(!page||window.__EAO_V11_PATCH__)return;window.__EAO_V11_PATCH__=true;
const head=page.querySelector('.page-head'),headActions=head?.querySelector('.page-actions'),mainGrid=page.querySelector(':scope > .grid-2'),formPanel=mainGrid?.querySelector(':scope > .panel.pad'),saveBtn=byId('saveEntry'),noPlanBtn=byId('noPlanBtn');
if(head){const p=head.querySelector('p');if(p)p.textContent='先判断今天的状态和方向，需要时用番茄钟保护执行；填写完成后在表单最下方保存。';}
let jumpSaved=byId('jumpSavedToday');if(!jumpSaved&&headActions){jumpSaved=document.createElement('button');jumpSaved.className='btn ghost';jumpSaved.id='jumpSavedToday';jumpSaved.textContent='已填写记录';headActions.insertBefore(jumpSaved,noPlanBtn||saveBtn||null);}
let savedStrip=byId('todaySavedStrip');if(!savedStrip&&head){savedStrip=document.createElement('div');savedStrip.className='today-saved-strip empty-state';savedStrip.id='todaySavedStrip';head.insertAdjacentElement('afterend',savedStrip);}
if(saveBtn&&formPanel&&!byId('todaySaveZone')){const z=document.createElement('div');z.className='form-save-zone';z.id='todaySaveZone';z.innerHTML='<div class="hint"><b>填完再保存。</b><br>草稿会自动保留；保存后才进入正式历史记录和长期模式分析。</div>';saveBtn.textContent='保存今天 ✓';z.appendChild(saveBtn);formPanel.appendChild(z);}
let panel=byId('pomodoroPanel');if(!panel&&mainGrid){panel=document.createElement('div');panel.className='panel pomodoro-panel';panel.id='pomodoroPanel';panel.innerHTML=`<div class="pomodoro-head"><div><div class="kicker">PLAN → FOCUS → EVIDENCE</div><h2>🍅 番茄钟</h2><p>先计划专注块，再记录真实完成数。它是保护注意力的工具，不是新的完成率。</p></div><button class="mini-btn" id="pomoUseAnchor">使用 Today Anchor</button></div><div class="pomo-layout"><div><div class="pomo-plan"><div class="field pomo-task-field"><label>本轮要推进什么？</label><input id="pomoTask" placeholder="例如：完成电源部分原理图检查"></div><div class="field"><label>计划番茄</label><input id="pomoPlanned" type="number" min="1" max="12" value="4"></div><div class="field"><label>专注 min</label><input id="pomoWorkMin" type="number" min="5" max="90" step="5" value="25"></div><div class="field"><label>休息 min</label><input id="pomoBreakMin" type="number" min="1" max="30" value="5"></div></div><div class="pomo-foot"><span id="pomoPlanHint">计划 4 个 × 25 分钟 = 100 分钟专注</span><button class="pomo-link" id="pomoClearToday">清零今日番茄</button></div></div><div class="pomo-timer"><div class="pomo-phase" id="pomoPhase">FOCUS · 专注</div><div class="pomo-clock" id="pomoClock">25:00</div><div class="pomo-progress" id="pomoProgress">已完成 0 / 计划 4</div><div class="pomo-dots" id="pomoDots"></div><div class="pomo-actions"><button class="btn primary" id="pomoStartPause">开始专注</button><button class="btn ghost" id="pomoFinish">完成本轮</button><button class="btn ghost" id="pomoReset">重置本轮</button></div></div></div>`;mainGrid.insertAdjacentElement('beforebegin',panel);}
const KEY2='eao_pomodoro_v11';let handle=null;const def=()=>({date:todayISO(),task:'',planned:4,completed:0,workMin:25,breakMin:5,phase:'work',running:false,remaining:1500,endAt:null});
function read(){try{let p=JSON.parse(storageGet(KEY2)||'null');if(!p)return def();if(p.date!==todayISO()&&!p.running){let d=def();d.planned=p.planned||4;d.workMin=p.workMin||25;d.breakMin=p.breakMin||5;return d}return Object.assign(def(),p)}catch(e){return def()}}let pomo=read();
const save=()=>storageSet(KEY2,JSON.stringify(pomo)),snap=()=>({planned:+pomo.planned||0,completed:+pomo.completed||0,workMin:+pomo.workMin||25,task:pomo.task||''}),secs=()=>pomo.running&&pomo.endAt?Math.max(0,Math.ceil((pomo.endAt-Date.now())/1000)):Math.max(0,+pomo.remaining||0),fmt=s=>`${String(Math.floor(s/60)).padStart(2,'0')}:${String(Math.max(0,s%60)).padStart(2,'0')}`;
function render(){if(!panel)return;const t=byId('pomoTask'),p=byId('pomoPlanned'),w=byId('pomoWorkMin'),b=byId('pomoBreakMin');if(document.activeElement!==t)t.value=pomo.task||'';if(document.activeElement!==p)p.value=pomo.planned||4;if(document.activeElement!==w)w.value=pomo.workMin||25;if(document.activeElement!==b)b.value=pomo.breakMin||5;byId('pomoClock').textContent=fmt(secs());byId('pomoPhase').textContent=pomo.phase==='break'?'BREAK · 恢复':'FOCUS · 专注';byId('pomoProgress').textContent=`已完成 ${pomo.completed||0} / 计划 ${pomo.planned||0}`;byId('pomoPlanHint').textContent=`计划 ${pomo.planned||0} 个 × ${pomo.workMin||25} 分钟 = ${(pomo.planned||0)*(pomo.workMin||25)} 分钟专注`;byId('pomoStartPause').textContent=pomo.running?'暂停':(pomo.phase==='break'?'开始休息':'开始专注');panel.classList.toggle('running',!!pomo.running);panel.classList.toggle('breaking',pomo.phase==='break');const n=Math.min(12,Math.max(1,+pomo.planned||1));byId('pomoDots').innerHTML=Array.from({length:n},(_,i)=>`<i class="pomo-dot ${i<(pomo.completed||0)?'done':(i===(pomo.completed||0)&&pomo.phase==='work'?'current':'')}"></i>`).join('');}
function sync(){if(pomo.running)return;const ow=pomo.workMin,ob=pomo.breakMin;pomo.task=byId('pomoTask').value.trim();pomo.planned=Math.min(12,Math.max(1,+byId('pomoPlanned').value||4));pomo.workMin=Math.min(90,Math.max(5,+byId('pomoWorkMin').value||25));pomo.breakMin=Math.min(30,Math.max(1,+byId('pomoBreakMin').value||5));if((pomo.phase==='work'&&ow!==pomo.workMin)||(pomo.phase==='break'&&ob!==pomo.breakMin))pomo.remaining=(pomo.phase==='work'?pomo.workMin:pomo.breakMin)*60;save();render();}
function done(auto){pomo.running=false;pomo.endAt=null;if(pomo.phase==='work'){pomo.completed=(pomo.completed||0)+1;const a=byId('actualMinutes');if(a){a.value=(+a.value||0)+(pomo.workMin||25);a.dispatchEvent(new Event('input',{bubbles:true}));}pomo.phase='break';pomo.remaining=(pomo.breakMin||5)*60;try{navigator.vibrate?.([120,70,120])}catch(e){}toast(auto?'一个番茄完成 🍅':'已完成本轮 🍅');}else{pomo.phase='work';pomo.remaining=(pomo.workMin||25)*60;toast('休息结束，下一轮按需要再开始');}save();render();renderTodayMirror();renderSaved();}
function tick(){if(!pomo.running)return;if(secs()<=0){done(true);return}render()}
['pomoTask','pomoPlanned','pomoWorkMin','pomoBreakMin'].forEach(id=>byId(id)?.addEventListener('change',sync));
byId('pomoUseAnchor')?.addEventListener('click',()=>{const a=byId('anchor')?.value.trim();if(!a)return toast('先填写 Today Anchor');pomo.task=a;save();render();toast('已把 Anchor 放入番茄钟')});
byId('pomoStartPause')?.addEventListener('click',()=>{sync();if(pomo.running){pomo.remaining=secs();pomo.running=false;pomo.endAt=null;toast('已暂停')}else{if(secs()<=0)pomo.remaining=(pomo.phase==='work'?pomo.workMin:pomo.breakMin)*60;pomo.running=true;pomo.endAt=Date.now()+pomo.remaining*1000;toast(pomo.phase==='work'?'开始专注':'开始休息')}save();render()});
byId('pomoFinish')?.addEventListener('click',()=>done(false));byId('pomoReset')?.addEventListener('click',()=>{pomo.running=false;pomo.endAt=null;pomo.remaining=(pomo.phase==='work'?pomo.workMin:pomo.breakMin)*60;save();render();toast('本轮已重置')});byId('pomoClearToday')?.addEventListener('click',()=>{const k={planned:pomo.planned,workMin:pomo.workMin,breakMin:pomo.breakMin,task:pomo.task};pomo=Object.assign(def(),k);save();render();renderSaved();toast('今日番茄计数已清零')});byId('anchor')?.addEventListener('change',()=>{if(!pomo.task){pomo.task=byId('anchor').value.trim();save();render()}});
const oldForm=formEntry;formEntry=function(){const e=oldForm(),p=snap();e.pomodoroPlanned=p.planned;e.pomodoroCompleted=p.completed;e.pomodoroWorkMin=p.workMin;e.pomodoroTask=p.task;return e};
const oldEntry=entryHTML;entryHTML=function(e){let h=oldEntry(e);if(e.pomodoroPlanned)h=h.replace('</p></div><div class="entry-score">',` · 🍅 ${e.pomodoroCompleted||0}/${e.pomodoroPlanned}</p></div><div class="entry-score">`);return h};
const oldLoad=loadEntryToForm;loadEntryToForm=function(e){if(e?.pomodoroPlanned){pomo.planned=e.pomodoroPlanned;pomo.completed=e.pomodoroCompleted||0;pomo.workMin=e.pomodoroWorkMin||25;pomo.task=e.pomodoroTask||e.anchor||'';pomo.running=false;pomo.phase='work';pomo.endAt=null;pomo.remaining=pomo.workMin*60;save();render()}return oldLoad(e)};
function renderSaved(){if(!savedStrip)return;const t=[...(data.entries||[])].sort((a,b)=>b.date.localeCompare(a.date)).find(e=>e.date===todayISO());if(t){savedStrip.classList.remove('empty-state');const pt=t.pomodoroPlanned?` · 🍅 ${t.pomodoroCompleted||0}/${t.pomodoroPlanned}`:'';savedStrip.innerHTML=`<div class="today-saved-copy"><b>今天已经保存过</b><p>${t.anchor?escapeHtml(t.anchor):'没有设置 Anchor'} · ⚡${t.energy} · 🎯${t.focus} · 一致感 ${t.alignment}/5${pt}</p></div><div class="today-saved-actions"><button class="mini-btn" id="editSavedToday">编辑今天</button><button class="mini-btn" id="jumpHistoryBtn">查看历史</button></div>`;byId('editSavedToday')?.addEventListener('click',()=>loadEntryToForm(t));}else{savedStrip.classList.add('empty-state');savedStrip.innerHTML='<div class="today-saved-copy"><b>今天还没有正式保存</b><p>草稿会自动保留；填写完成后使用表单最下方的“保存今天”。</p></div><div class="today-saved-actions"><button class="mini-btn" id="jumpHistoryBtn">查看历史</button></div>';}byId('jumpHistoryBtn')?.addEventListener('click',()=>byId('allEntries')?.scrollIntoView({behavior:'smooth',block:'start'}));}
const oldHist=renderTodayHistory;renderTodayHistory=function(){oldHist();renderSaved()};jumpSaved?.addEventListener('click',()=>savedStrip?.scrollIntoView({behavior:'smooth',block:'center'}));
const oldMirror=renderTodayMirror;renderTodayMirror=function(){oldMirror();const p=snap(),box=byId('smartReflection');if(box&&p.planned){let n=byId('pomoReflectionNote');if(!n){n=document.createElement('div');n.className='reflection-step';n.id='pomoReflectionNote';box.appendChild(n)}n.innerHTML=`<b>POMODORO · EXECUTION</b><p>计划 ${p.planned} 个，目前完成 ${p.completed} 个。这里只把它当作实际执行证据，不作为绩效分数。</p>`}};
render();renderSaved();renderTodayHistory();renderTodayMirror();handle=setInterval(tick,1000);
})();