/* My OS V12 · Universal UX Rebuild */
(function(){
'use strict';
if(window.__MY_OS_V12__)return;window.__MY_OS_V12__=true;
const PROFILE_KEY='my_os_profile_v12';
const P=()=>({guide:'options',contexts:[],envs:[],note:'',need:'',onboarded:false});
function readP(){try{return Object.assign(P(),JSON.parse(storageGet(PROFILE_KEY)||'{}'))}catch(e){return P()}}let profile=readP();
const L={guide:{lead:'直接带着我做',options:'给我几个选择',analyze:'帮我分析',check:'我自己规划'},contexts:{work:'上班',study:'上学/考试',care:'带孩子/照护',family:'伴侣/家庭',freelance:'自由职业/生意',create:'兴趣/创作',health:'健康/恢复',retired:'退休/慢生活',travel:'经常出差',shift:'倒班/夜班',irregular:'作息不固定',social:'社交很多'},envs:{office:'办公室',home:'家',commute:'通勤',school:'学校',outside:'外面',travel:'出差/旅行',mixed:'经常切换'}};
const q=s=>document.querySelector(s),qa=s=>[...document.querySelectorAll(s)];
function openM(id){q('#'+id)?.classList.add('show')}function closeM(id){q('#'+id)?.classList.remove('show')}
function saveP(){storageSet(PROFILE_KEY,JSON.stringify(profile));renderProfile();renderSupport()}
function mk(tag,attrs={},html=''){const e=document.createElement(tag);Object.entries(attrs).forEach(([k,v])=>k==='class'?e.className=v:e.setAttribute(k,v));e.innerHTML=html;return e}
const brand=q('.brand b'),small=q('.brand small'),crumb=q('.crumb'),rt=q('#runtimeBadge span');if(brand)brand.textContent='My OS';if(small)small.textContent='V12 · Adaptive Life · 因人而变';if(crumb)crumb.textContent=' · 不要求先学会规划，先解决你现在的问题';if(rt)rt.textContent='V12 · My OS';document.title='My OS · 今天';
const nav=q('#sideNav');if(nav){nav.innerHTML=`<button data-page="dashboard" class="active"><i>⌂</i>今天</button><button data-page="today"><i>✓</i>计划与专注</button><button data-page="discoveries"><i>✨</i>发现</button><button data-page="manual"><i>◉</i>我的</button><details class="nav-more"><summary>更多工具</summary><button data-page="experiments"><i>↻</i>试一试</button><button data-page="calibration"><i>⌁</i>计划得准吗</button><button data-page="projects"><i>▤</i>正在做的事</button><button data-page="book"><i>▦</i>生活使用指南</button><button data-page="method"><i>◎</i>方法速查</button></details>`}
const mn=q('#mobileNav');if(mn)mn.innerHTML=`<button data-page="dashboard" class="active"><i>⌂</i>今天</button><button data-page="today"><i>✓</i>要做的</button><button data-page="discoveries"><i>✨</i>发现</button><button data-page="manual"><i>◉</i>我的</button>`;
if(typeof titles==='object')Object.assign(titles,{dashboard:'今天',today:'计划与专注',calibration:'计划得准吗',discoveries:'发现',experiments:'试一试',projects:'正在做的事',manual:'我的',book:'生活使用指南',method:'方法速查'});
const dash=q('#page-dashboard'),dh=dash?.querySelector('.page-head'),hero=dash?.querySelector('.panel.hero');
if(dh)dh.innerHTML=`<div><div class="kicker">START WHERE YOU ARE</div><h1>今天你需要什么？</h1><p>不用先学时间管理，也不用先建立目标。选一个最接近你现在的状态，My OS 会用适合你的方式开始。</p></div><div class="page-actions"><button class="btn ghost" id="openOnboarding">调整我的使用方式</button></div>`;
if(hero)hero.innerHTML=`<span class="tag">30秒开始</span><h2>你不需要适应系统，系统应该适应你。</h2><p>不同性格、身份、生活责任、作息和环境，需要不同的方法。这里没有唯一正确的日程表，也不会根据性别或职业自动给你贴标签。</p><div class="need-grid" id="needGrid"><button class="need-card" data-need="messy"><span class="need-icon">😵</span><div><b>有点乱，帮我理一理</b><small>先把脑子里的事倒出来，不要求你先分类。</small></div></button><button class="need-card" data-need="do"><span class="need-icon">🚀</span><div><b>我想推进一件事</b><small>快速选一件最值得的事，必要时进入专注。</small></div></button><button class="need-card" data-need="tired"><span class="need-icon">😴</span><div><b>今天有点累</b><small>先判断是身体、脑力还是情绪需要恢复。</small></div></button><button class="need-card" data-need="plan"><span class="need-icon">📋</span><div><b>我想安排一下今天</b><small>给喜欢结构的人一个轻量日计划。</small></div></button><button class="need-card" data-need="stuck"><span class="need-icon">🧠</span><div><b>有件事一直拖着</b><small>先找出是难启动、资源不够，还是已经不值得。</small></div></button><button class="need-card" data-need="easy"><span class="need-icon">🌿</span><div><b>今天想轻松一点</b><small>把恢复、关系和娱乐也当成正常生活。</small></div></button><button class="need-card" data-need="talk"><span class="need-icon">💬</span><div><b>我也不知道，聊聊吧</b><small>不填表，先从一句话开始。</small></div></button></div><div class="support-summary" id="supportSummary"></div>`;
const td=q('#page-today');if(td){const k=td.querySelector('.page-head .kicker'),h=td.querySelector('.page-head h1'),p=td.querySelector('.page-head p');if(k)k.textContent='看看自己 · 选一件事 · 做一点 · 回头看看';if(h)h.textContent='计划与专注';if(p)p.textContent='想计划就计划，不想计划也可以。先写今天最值得的一件事，需要时用“专注一会儿”。';const ph=td.querySelector('.pomodoro-head h2'),pp=td.querySelector('.pomodoro-head p'),pu=q('#pomoUseAnchor');if(ph)ph.textContent='⏱ 专注一会儿';if(pp)pp.textContent='需要时用一个明确的专注时段保护注意力；25+5 只是可选的番茄模式，不是必须。';if(pu)pu.textContent='使用“今天最值得的一件事”';}
const rep=[['Engineer Adaptive OS','My OS'],['系统学习手册','生活使用指南'],['系统学习','生活使用指南'],['我的说明书','我的使用说明'],['项目 / Resume','正在做的事'],['校准 / 中断','计划得准吗'],['Today Anchor','今天最值得的一件事'],['Resume Point','下次从这里继续'],['工程师专用机制','复杂任务与高打断环境'],['工程师时间管理','个人时间管理'],['所有工程师','所有人']];
const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);let node;const nodes=[];while(node=walker.nextNode())if(!['SCRIPT','STYLE'].includes(node.parentElement?.tagName))nodes.push(node);nodes.forEach(n=>{let s=n.nodeValue;rep.forEach(([a,b])=>s=s.split(a).join(b));if(s!==n.nodeValue)n.nodeValue=s});
const book=q('#page-book');if(book&&!q('#problemGuide')){const ph=book.querySelector('.page-head');if(ph){const h=ph.querySelector('h1'),p=ph.querySelector('p'),k=ph.querySelector('.kicker');if(k)k.textContent='LIFE GUIDE · 按问题学习';if(h)h.textContent='生活使用指南';if(p)p.textContent='不要求从头读。可以从真实问题进入；想系统学习时再走完整路线。';const box=mk('div',{class:'problem-guide panel pad',id:'problemGuide'},`<div class="kicker">按你正在遇到的问题开始</div><div class="problem-grid"><button class="problem-chip" data-open-chapter="book-ch-23">我总是拖延</button><button class="problem-chip" data-open-chapter="book-ch-13">事情太多，脑子很乱</button><button class="problem-chip" data-open-chapter="book-ch-20">计划总被打乱</button><button class="problem-chip" data-open-chapter="book-ch-35">工作/学习很累</button><button class="problem-chip" data-open-chapter="book-ch-15">想兼顾家庭和自己</button><button class="problem-chip" data-open-chapter="book-ch-29">不知道怎么真正休息</button><button class="problem-chip" data-open-chapter="book-ch-25">三分钟热度</button><button class="problem-chip" data-open-chapter="book-ch-14">生活没有规律</button></div>`);ph.after(box)}}
const man=q('#page-manual');if(man&&!q('#contextProfile')){const ph=man.querySelector('.page-head');if(ph){const h=ph.querySelector('h1'),p=ph.querySelector('p'),k=ph.querySelector('.kicker');if(k)k.textContent='MY WAY · 不是人格标签';if(h)h.textContent='我的使用说明';if(p)p.textContent='这里记录的是你自己确认过的规律、偏好和当前生活条件。它们可以随身份、环境和人生阶段变化。';ph.after(mk('div',{class:'panel pad context-profile',id:'contextProfile'},`<div class="section-title"><div><h2>我的情况与偏好</h2><p>身份是背景，不是标签；性别是可选信息，不自动决定方法；真正影响建议的是责任、环境、精力和使用偏好。</p></div><button class="btn ghost" id="editProfileBtn">调整</button></div><div id="profileSummary"></div>`))}}
if(!q('#nowHelpBtn'))document.body.insertAdjacentHTML('beforeend',`<button class="now-help-btn" id="nowHelpBtn">✨<span>我现在该做什么</span></button>`);
if(!q('#onboardingModal'))document.body.insertAdjacentHTML('beforeend',`<div class="modal-bg" id="onboardingModal"><div class="modal universal-modal"><div class="modal-head"><div><div class="kicker">30秒设置</div><h2>你希望 My OS 怎么帮你？</h2></div><button class="icon-btn" data-close="onboardingModal">×</button></div><div class="u-step"><b>1 · 我希望系统介入多少</b><div class="choice-grid single" id="guideChoices"><button data-guide="lead">直接带着我做<small>我不想先规划</small></button><button data-guide="options">给我几个选择<small>我自己决定</small></button><button data-guide="analyze">帮我分析<small>不要替我安排</small></button><button data-guide="check">我自己规划<small>你帮我检查</small></button></div></div><div class="u-step"><b>2 · 最近我的生活主要包含</b><div class="choice-grid multi" id="contextChoices"><button data-context="work">💼 上班</button><button data-context="study">🎓 上学/考试</button><button data-context="care">👶 带孩子/照护</button><button data-context="family">❤️ 伴侣/家庭</button><button data-context="freelance">💰 自由职业/生意</button><button data-context="create">🎨 兴趣/创作</button><button data-context="health">🌿 健康/恢复</button><button data-context="retired">☕ 退休/慢生活</button><button data-context="travel">✈️ 经常出差</button><button data-context="shift">🌙 倒班/夜班</button><button data-context="irregular">🔄 作息不固定</button><button data-context="social">🧑‍🤝‍🧑 社交很多</button></div></div><div class="u-step"><b>3 · 我通常在哪些环境里安排事情</b><div class="choice-grid multi" id="environmentChoices"><button data-env="office">🏢 办公室</button><button data-env="home">🏠 家</button><button data-env="commute">🚆 通勤</button><button data-env="school">🏫 学校</button><button data-env="outside">☕ 外面</button><button data-env="travel">🧳 出差/旅行</button><button data-env="mixed">🔀 经常切换</button></div></div><div class="u-step"><label class="optional-profile"><span>其他情况（可选）</span><textarea id="profileNote" placeholder="例如：晚上经常被打断；最近处于冲刺期；我一看到复杂计划就压力大……"></textarea></label><p class="privacy-note">性别等个人信息不是必填项。只有当你主动告诉系统某项因素确实影响你的时间、精力或生活安排时，才应把它纳入建议。</p></div><button class="btn primary full" id="saveProfileBtn">保存并开始</button></div></div><div class="modal-bg" id="quickHelpModal"><div class="modal universal-modal"><div class="modal-head"><div><div class="kicker">RIGHT NOW</div><h2>我现在该做什么？</h2></div><button class="icon-btn" data-close="quickHelpModal">×</button></div><div id="quickHelpBody"></div></div></div>`);
function sync(){qa('[data-guide]').forEach(b=>b.classList.toggle('selected',b.dataset.guide===profile.guide));qa('[data-context]').forEach(b=>b.classList.toggle('selected',profile.contexts.includes(b.dataset.context)));qa('[data-env]').forEach(b=>b.classList.toggle('selected',profile.envs.includes(b.dataset.env)));if(q('#profileNote'))q('#profileNote').value=profile.note||''}
function renderSupport(){const b=q('#supportSummary');if(!b)return;const c=profile.contexts.slice(0,4).map(x=>L.contexts[x]).filter(Boolean);b.innerHTML=profile.onboarded?`当前帮助方式：<b>${L.guide[profile.guide]}</b>${c.length?` · 最近生活：${c.join('、')}`:''}。这些都可以随时改变。`:'首次使用只需告诉我：你希望我多主动，以及你最近的生活处境。'}
function renderProfile(){const b=q('#profileSummary');if(!b)return;const chips=[`帮助方式：${L.guide[profile.guide]}`,...profile.contexts.map(x=>L.contexts[x]),...profile.envs.map(x=>L.envs[x])].filter(Boolean);b.innerHTML=`<div class="profile-chips">${chips.map(x=>`<span class="profile-chip">${escapeHtml(x)}</span>`).join('')||'<span class="muted">还没有设置；这不会影响基本使用。</span>'}</div>${profile.note?`<div class="profile-note">你补充的情况：${escapeHtml(profile.note)}</div>`:''}<div class="identity-note">系统不会因为性别、职业或身份自动决定你“应该怎样生活”。只有你主动说明某个因素会影响时间、精力、照护责任或环境时，它才应进入建议。</div>`}
function need(k){profile.need=k;saveP();qa('[data-need]').forEach(b=>b.classList.toggle('selected',b.dataset.need===k));const a={messy:()=>{go('today');setTimeout(()=>{const r=q('#review');if(r){r.focus();r.placeholder='把脑子里惦记的事情随便写下来，不用分类。'}},80)},do:()=>{go('today');setTimeout(()=>q('#anchor')?.focus(),80)},tired:()=>{go('today');toast('今天先把状态放在任务前面。')},plan:()=>{go('today');setTimeout(()=>q('#anchor')?.focus(),80)},stuck:()=>{go('today');setTimeout(()=>{const r=q('#review');if(r){r.focus();r.placeholder='这件事卡在哪里？不知道怎么开始 / 太累 / 太大 / 已经不重要？'}},80)},easy:()=>{go('today');toast('今天可以把恢复、关系或娱乐当成正式选择。')},talk:()=>{go('today');setTimeout(()=>{const r=q('#review');if(r){r.focus();r.placeholder='随便说说最近怎么样，不需要先想清楚。'}},80)}};a[k]?.()}
function quick(){const e=typeof formEntry==='function'?formEntry():null,energy=e?.energy||3,stress=e?.stress||3,anchor=e?.anchor||'';let o;if(energy<=2||stress>=4)o=[['先把要求缩小','只保留真正必须的一件事，其他先放下。','today'],['做一个低脑力版本','如果必须推进，把任务缩成整理、准备、确认下一步。','today'],['今天到这里','如果没有必须事项，恢复也是合理产出。','dashboard']];else if(anchor)o=[['先专注一小段',`你已经写了“${anchor}”。先从20–25分钟开始。`,'today'],['把它缩成下一步','如果还不想开始，先问：打开以后第一步是什么？','today'],['重新考虑它','如果它已经不重要，可以调整或放弃。','discoveries']];else o=[['选今天最值得的一件事','不列长清单，只选一个结果。','today'],['先把脑子里的事倒出来','事情太多时，不用排序，先全部写出来。','today'],['今天不计划','如果今天不需要结构，也可以只在晚上回顾。','today']];q('#quickHelpBody').innerHTML=`<p class="muted">先给三个选择，没有哪一个是“正确答案”。</p><div class="quick-options">${o.map((x,i)=>`<div class="quick-option"><b>${i+1}. ${escapeHtml(x[0])}</b><p>${escapeHtml(x[1])}</p><button class="btn ${i?'ghost':'primary'}" data-quick-go="${x[2]}">选这个</button></div>`).join('')}</div>`;openM('quickHelpModal')}
qa('[data-need]').forEach(b=>b.addEventListener('click',()=>need(b.dataset.need)));q('#openOnboarding')?.addEventListener('click',()=>{sync();openM('onboardingModal')});q('#editProfileBtn')?.addEventListener('click',()=>{sync();openM('onboardingModal')});q('#nowHelpBtn')?.addEventListener('click',quick);qa('[data-guide]').forEach(b=>b.addEventListener('click',()=>{profile.guide=b.dataset.guide;sync()}));qa('[data-context]').forEach(b=>b.addEventListener('click',()=>{const x=b.dataset.context;profile.contexts=profile.contexts.includes(x)?profile.contexts.filter(v=>v!==x):[...profile.contexts,x];sync()}));qa('[data-env]').forEach(b=>b.addEventListener('click',()=>{const x=b.dataset.env;profile.envs=profile.envs.includes(x)?profile.envs.filter(v=>v!==x):[...profile.envs,x];sync()}));q('#saveProfileBtn')?.addEventListener('click',()=>{profile.note=q('#profileNote')?.value.trim()||'';profile.onboarded=true;saveP();closeM('onboardingModal');toast('已保存；以后可以随时调整')});q('#quickHelpBody')?.addEventListener('click',e=>{const b=e.target.closest('[data-quick-go]');if(!b)return;closeM('quickHelpModal');go(b.dataset.quickGo)});qa('[data-open-chapter]').forEach(b=>b.addEventListener('click',()=>window.__eaoOpenReader?.(b.dataset.openChapter)));['onboardingModal','quickHelpModal'].forEach(id=>{const m=q('#'+id);m?.addEventListener('click',e=>{if(e.target===m)closeM(id)});m?.querySelector('[data-close]')?.addEventListener('click',()=>closeM(id))});
const dm=q('#dataModal p.muted');if(dm)dm.textContent='数据默认保存在当前浏览器。你可以导出 JSON 做备份，或在其他设备导入。这里不要求你理解任何版本迁移。';
renderProfile();renderSupport();if(profile.need)q(`[data-need="${profile.need}"]`)?.classList.add('selected');setTimeout(()=>{if(!profile.onboarded){sync();openM('onboardingModal')}},250);
})();
