/* My OS V22 · Knowledge Content Enhancement Runtime */
(function(){
'use strict';
if(window.__MY_OS_V22__) return;
window.__MY_OS_V22__=true;

const STATE_KEY='my_os_learning_v22';
const GUIDE_KEY='my_os_v22_learning_guide_seen';
const PROFILE_KEY='my_os_profile_v12';
const CORE_KEY='eao_v4_data';
const q=s=>document.querySelector(s), qa=s=>[...document.querySelectorAll(s)];
const sget=k=>{try{return typeof storageGet==='function'?storageGet(k):localStorage.getItem(k)}catch(e){return null}};
const sset=(k,v)=>{try{if(typeof storageSet==='function')storageSet(k,v);else localStorage.setItem(k,v)}catch(e){}};
const jread=(k,d)=>{try{const v=JSON.parse(sget(k)||'null');return v==null?d:v}catch(e){return d}};
const esc=s=>typeof escapeHtml==='function'?escapeHtml(String(s??'')):String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const now=()=>Date.now();
const DAY=86400000;

function defaultState(){return {learned:{},applied:{},quiz:{},history:[],tab:'route'};}
function state(){return Object.assign(defaultState(),jread(STATE_KEY,{}));}
function save(st){sset(STATE_KEY,JSON.stringify(st));}

const PERSONAS=[
 {id:'student',icon:'🎓',name:'学生 / 考试',desc:'课程、考试、技能学习'},
 {id:'work',icon:'💼',name:'职场 / 管理',desc:'任务、会议、协作和交付'},
 {id:'care',icon:'👶',name:'照护 / 家庭',desc:'时间经常被他人需要打断'},
 {id:'free',icon:'🧭',name:'自由职业 / 创作',desc:'自主度高，但外部边界少'},
 {id:'slow',icon:'🌿',name:'退休 / 慢生活',desc:'不以产出最大化为中心'}
];

const TOPICS={
 activation:{icon:'▶️',title:'启动与拖延',chapter:'book-ch-23',short:'知道该做，却迟迟开始时，先降低启动摩擦，而不是先提高意志力。',principle:'“开始不了”不是一个单一问题。先区分任务不清楚、任务太大、资源不足、价值冲突和环境打断，再选择方法。',misconceptions:['误区：拖延就是自控力差。很多时候真正的问题是下一步不清楚或启动成本太高。','误区：越重要的任务越应该一次做久一点。重要任务反而更容易因为压力过大而难启动。','误区：必须先有动力才能开始。很多动力是在行动产生反馈之后才出现。'],steps:['把目标改写成“下一步看得见的动作”','把第一轮缩到10–20分钟，先获得启动证据','如果精力低，改成低脑力版本而不是硬顶','结束前写一句“下次从哪里继续”'],tree:[['我不知道从哪开始','只定义一个看得见的下一步，不做完整计划。'],['知道怎么做，但任务太大','把第一步缩成10分钟内能完成的动作。'],['身体/脑子明显很累','先选低认知负荷版本，必要时恢复。'],['其实不想做','检查价值、后果和是否可以缩小/延后/放弃。'],['总被打断','设计可中断版本，并留下 Resume Point。']],cases:{student:'复习一整章迟迟不开始 → 不要求“学完一章”，先做5道题找薄弱点。',work:'报告一直拖着 → 先只写标题、结论草稿和需要补的数据，不要求一次成稿。',care:'孩子随时可能叫人 → 先做10分钟可暂停的部分，并在停下前写下一步。',free:'没有人催的个人项目 → 先设一个45分钟“交付给自己”的小截止点。',slow:'想学摄影但总搁置 → 不设高强度计划，先安排一次20分钟实际拍摄。'},quiz:{q:'下面哪种做法最符合“降低启动摩擦”？',options:['先制定完整的一周计划','等待状态变好再开始','把任务改成10分钟内可见的下一步','用更严格的惩罚逼自己'],correct:2,explain:'启动困难时，最有效的第一步通常是降低行动门槛并获得真实反馈，而不是继续增加规划和压力。'},apply:'把今天最重要的事情改写成一个10–20分钟内能开始的“下一步动作”。'},
 planning:{icon:'🧩',title:'计划与现实',chapter:'book-ch-20',short:'好的计划不是预测未来，而是给现实变化留出调整空间。',principle:'计划应该表达优先级、资源和备用路径，而不是把未来每一分钟都假装成确定的。',misconceptions:['误区：计划越详细越可靠。环境越不稳定，过细计划越容易产生维护成本。','误区：偏离计划代表执行失败。偏差是校准估时、环境和资源的重要数据。','误区：空白时间等于浪费。缓冲是系统可靠性的一部分。'],steps:['先区分必须做、值得做、可以不做','根据时间自主度选择固定时间块或触发式计划','为高打断日准备10/30/60分钟版本','至少保留一段缓冲，不把可用时间排满'],tree:[['时间自主度高、打断少','可以使用时间块，但仍保留缓冲。'],['时间自主度低','用事件触发：“会议后/孩子睡后/到酒店后”启动。'],['打断很多','准备10/30/60分钟三个版本。'],['总是做不完','减少同时推进数量，并检查估时偏差。'],['临时事项很多','先预留缓冲，再安排非必须事项。']],cases:{student:'课表固定但作业波动 → 用“课后第一个空档”而不是死守20:00。',work:'会议很多 → 只保护1–2个关键输出窗口，其余按会议间隙安排。',care:'家庭时间不可预测 → 不排固定两小时，改成10/30/60分钟三个版本。',free:'时间看似很多 → 给自主工作设置开始/结束边界，避免无限延长。',slow:'没有硬截止期 → 用“今天想体验什么”代替把整天排满。'},quiz:{q:'高打断环境下，更合适的计划通常是？',options:['把每小时都排满','只做长期目标，不安排当天','准备不同长度的可中断版本','每天都使用完全相同的时间表'],correct:2,explain:'高打断环境的关键不是提高计划精度，而是让任务能在不同长度的现实窗口中继续。'},apply:'为今天的一件重要事情准备“10分钟版 / 30分钟版 / 有完整时间版”。'},
 recovery:{icon:'🌿',title:'恢复与休息',chapter:'book-ch-29',short:'恢复不是做完任务后的奖励，而是维持注意力、情绪和判断能力的基础条件。',principle:'“没工作”不一定等于恢复。恢复要匹配消耗类型：睡眠不足、认知过载、情绪消耗、社交过载和身体疲劳需要不同方式。',misconceptions:['误区：刷手机就是休息。高刺激输入有时会继续消耗注意力。','误区：必须先完成所有事情才配休息。资源不足会直接降低后续决策质量。','误区：恢复就是完全静止。散步、轻运动、换环境也可能是恢复。'],steps:['先识别主要是哪一种消耗','睡眠不足优先处理睡眠，而不是靠刺激顶住','认知过载时减少输入和切换','恢复后逐步回到中等负荷，不立刻补偿性加码'],tree:[['困、反应慢、睡眠不足','优先睡眠和降低安全风险。'],['脑子塞满、无法思考','减少输入、切换和决策数量。'],['情绪耗竭','选择安全的独处或支持性交流。'],['身体坐太久、发僵','轻运动、散步或换环境。'],['只是逃避某件事','先做10分钟启动测试，再判断是否真的需要恢复。']],cases:{student:'复习到脑子发木 → 不再刷知识点，先离屏走动并补足睡眠。',work:'连续会议后无法写方案 → 先做15分钟低刺激过渡，再进入深度任务。',care:'整天照护后情绪被掏空 → 恢复目标不是“再完成家务”，而是争取一段无需响应别人的时间。',free:'工作和生活边界混在一起 → 明确当天收工信号，避免“随时都还能做一点”。',slow:'空闲很多却仍疲惫 → 区分无聊、缺活动和真正疲劳，恢复不等于一直躺着。'},quiz:{q:'哪一种更接近“有效恢复”？',options:['不管多累都先把清单清空','根据消耗类型选择恢复方式','只要没有工作就算恢复','状态一好马上把之前少做的全部补回来'],correct:1,explain:'恢复需要匹配消耗类型，并避免刚恢复就立刻补偿性加码。'},apply:'现在判断自己最主要的消耗是：睡眠 / 认知 / 情绪 / 社交 / 身体，然后只选一个对应恢复动作。'},
 motivation:{icon:'🔥',title:'动力与持续',chapter:'book-ch-25',short:'长期持续更依赖环境、反馈和价值，而不是每天保持高昂情绪。',principle:'动力问题至少要区分“启动失败、资源不匹配、价值不匹配”。不同原因用同一种“坚持”策略，效果往往很差。',misconceptions:['误区：三分钟热度说明不够自律。很多计划本身没有反馈、边界或现实资源。','误区：兴趣项目也要像工作一样KPI化。过度考核可能破坏内在动机。','误区：中断几天就前功尽弃。长期系统应该允许恢复和重新进入。'],steps:['先判断是不想开始、没资源，还是目标本身不值得','把反馈周期缩短，让行动尽快产生可见结果','给自主项目设置轻边界，而不是无限开放','允许暂停和重新选择目标'],tree:[['很想做，但总不开始','处理启动线索和第一步。'],['开始后很快耗尽','检查任务难度和资源是否匹配。'],['越做越不想做','重新评估价值，不默认必须坚持。'],['没有外部截止期','建立轻量交付点和反馈。'],['兴趣被计划压得没意思','降低考核感，保留探索和自由。']],cases:{student:'想学语言但只靠热情 → 固定一个很小的使用场景，例如每天听懂一段真实材料。',work:'职业证书学两周就停 → 把目标从“坚持学习”改成每周完成一个可验证小模块。',care:'私人目标总让位给家庭 → 设最低版本，不要求每次都完整执行。',free:'个人产品没人催 → 每周做一个能被别人看到的小交付。',slow:'兴趣不是为了变现 → 允许只追求体验、作品和社交连接，不必产出KPI。'},quiz:{q:'长期动力下降时，第一步更应该做什么？',options:['加大惩罚','判断是启动、资源还是价值问题','把目标拆得越细越好','要求自己每天保持同样热情'],correct:1,explain:'动力下降可能来自不同机制，先分类才能选择合适方法。'},apply:'给当前一个长期目标写下：我是真的想做，还是只是觉得“应该做”？再决定继续、缩小或暂停。'},
 interruption:{icon:'🔀',title:'高打断环境与可恢复计划',chapter:'book-ch-20',short:'无法消灭打断时，真正有用的是降低“被打断后的恢复成本”。',principle:'高打断环境不适合照搬低打断环境的深度工作规范。关键是任务可中断、上下文可恢复、窗口长度可变化。',misconceptions:['误区：被打断就是注意力管理失败。照护、客服、管理等角色的打断本来就是现实组成。','误区：每次都重新从头进入状态。可以用 Resume Point 保存上下文。','误区：只有完整一小时才值得开始。短窗口也能推进准备、检查和局部工作。'],steps:['把任务拆成可暂停的小段','准备10/30/60分钟不同版本','中断前写下一步和关键上下文','恢复时先读Resume Point，不重新浏览全部材料'],tree:[['打断是工作/照护职责本身','接受其合法性，优化恢复成本。'],['打断来自可关闭通知','建立短时间保护窗口。'],['窗口长度完全不确定','优先可暂停任务。'],['恢复后总忘记做到哪','强制留下Resume Point。'],['一天切换很多领域','限制同时活跃的复杂任务数量。']],cases:{student:'宿舍/社团经常被叫走 → 做题前写当前题号和卡住点，中断后直接回来。',work:'管理者消息很多 → 把需要连续思考的任务集中到少量保护窗口，其余工作设计为可切换。',care:'照护孩子 → 不把孩子叫人视为“破坏计划”，任务本身必须可暂停。',free:'自己主动频繁切应用 → 先区分外部打断和自我打断，后者可以用环境限制。',slow:'家庭事务随机出现 → 用“有空就做哪个长度版本”，避免把生活变成迟到的日程表。'},quiz:{q:'高打断环境里最重要的设计之一是？',options:['要求完全不被打断','只做5分钟任务','保存清楚的恢复点','每天减少所有家庭事务'],correct:2,explain:'Resume Point 能显著降低重新理解上下文的成本，让不可避免的打断不至于让任务每次归零。'},apply:'今天每次停下复杂任务前，只写一句：“下次回来先做_____”。'},
 learning:{icon:'🎓',title:'学习启动与有效练习',chapter:'book-ch-23',short:'学习不是“坐了多久”，而是有没有产生提取、反馈和纠错。',principle:'当目标是掌握知识，主动回忆、自测、反馈和间隔重复通常比单纯重复阅读更有价值。',misconceptions:['误区：看得熟就等于会了。熟悉感和能独立提取不是一回事。','误区：一次学得越久越好。疲劳会降低后半段学习质量。','误区：先把所有内容看完再做题。测试本身就是学习过程。'],steps:['先用问题或自测找薄弱点','学习后闭卷复述或做题','记录错误原因而不只是答案','隔一段时间再提取，而不是当天重复看很多遍'],tree:[['完全不会','先建立最小概念框架，再做简单提取。'],['看懂但做不出','减少重读，增加闭卷回忆和题目。'],['错误反复出现','建立错误类型和纠错规则。'],['容易疲劳','缩短单次时长，提高反馈密度。'],['考试临近','按高频薄弱点和真题反馈排序。']],cases:{student:'复习考试 → 从真题/自测开始找薄弱点，再回教材补洞。',work:'学新软件 → 每学一个功能立刻用真实任务操作一次。',care:'时间碎片化 → 用短小知识卡和主动回忆，不要求完整长课。',free:'自学新技能 → 每周做一个小作品，让技能进入真实反馈。',slow:'兴趣学习 → 允许慢节奏，但仍用“讲给别人听/实际做一次”检验理解。'},quiz:{q:'“看起来很熟，但一合上书就说不出来”最说明什么？',options:['学习时间不够','熟悉感不等于能提取','应该继续重读同一页','必须一次学习两小时'],correct:1,explain:'能否在没有提示时提取信息，是比“看着熟”更可靠的掌握信号。'},apply:'今天学完一个知识点后，合上资料，用自己的话写3句核心内容。'},
 irregular:{icon:'🌙',title:'不规律作息与弹性结构',chapter:'book-ch-14',short:'倒班、出差和作息变化大时，固定钟点计划往往不如事件触发和窗口计划。',principle:'稳定结构不等于固定时间。可以稳定“触发条件、最低版本和恢复顺序”，即使每天钟点不同。',misconceptions:['误区：只要够自律就能每天同一时间做事。现实约束可能根本不允许。','误区：行程变化时原计划失败。可以保留行为顺序而不是保留具体钟点。','误区：旅行/倒班时要补齐所有日常习惯。阶段性减负更现实。'],steps:['把固定时间改成事件触发','保留1–2个核心最低版本','优先保护睡眠、饮食和关键恢复','环境恢复稳定后再逐步加回非核心事项'],tree:[['每天时间不同但事件顺序相似','用“下班后/到酒店后/早餐后”触发。'],['跨时区或夜班','优先恢复与安全，不追求完整习惯。'],['行程非常满','只保留最低版本和必须事项。'],['偶尔变化','固定时间计划可保留，但准备备用窗口。'],['长期不规律','定期复盘哪个触发最可靠。']],cases:{student:'课程表每天不同 → 用“当天最后一节课后”作为复习触发。',work:'经常出差 → 到酒店后只做20分钟整理和明日准备，不复制办公室完整流程。',care:'孩子作息变化 → 用“出现第一个稳定窗口”代替固定晚间时间。',free:'接单节奏不稳定 → 以交付节点和收工仪式建立边界。',slow:'生活时间自由但不固定 → 选事件触发保留喜欢的活动，不必追求钟点一致。'},quiz:{q:'作息非常不规律时，更稳定的计划锚点可能是？',options:['每天固定20:00','一个现实事件之后','把所有习惯取消','每天重新做完整计划'],correct:1,explain:'事件触发能在钟点变化时保留行为结构，例如“下班后”“到酒店后”“早餐后”。'},apply:'把一个总失败的固定时间计划改写成“发生_____之后，我做_____的最低版本”。'},
 estimation:{icon:'⏱️',title:'估时与计划校准',chapter:'book-ch-20',short:'估时不是一次猜准，而是持续用实际数据校准自己的计划密度。',principle:'很多计划失败并不是执行力不足，而是系统性低估准备、切换、沟通、返工和收尾时间。',misconceptions:['误区：总超时说明动作太慢。也可能是估时模型遗漏了隐性步骤。','误区：以后简单把所有任务乘2就行。不同任务类型需要不同校准。','误区：计划时间只算“真正做事”的分钟。准备、等待和收尾也占真实资源。'],steps:['记录计划时间和实际时间','按任务类型看偏差，而不是只看总平均','把准备、沟通、返工和收尾纳入估时','证据稳定后再形成个人倍率或缓冲规则'],tree:[['所有任务都超时','先检查计划是否长期排得过满。'],['只有某类任务超时','为该任务类型单独建立倍率。'],['常被临时事项影响','把缓冲从任务估时中分离出来。'],['第一次做的新任务','使用范围估计，不假装精确。'],['估时已经比较稳定','减少记录频率，只在明显偏差时再校准。']],cases:{student:'以为作业30分钟 → 把找资料、检查和提交也算进去。',work:'方案“写2小时” → 把沟通确认、数据等待和修改轮次纳入。',care:'计划只按自己时间估 → 加上照护切换和恢复上下文的成本。',free:'客户项目经常拖期 → 按项目类型积累真实交付倍率。',slow:'兴趣项目不需精确估时 → 只有当估时影响体验或承诺时才值得记录。'},quiz:{q:'长期估时偏短时，更好的第一步是？',options:['要求自己做快一点','把所有任务统一乘3','按任务类型比较计划与实际偏差','不再做任何计划'],correct:2,explain:'先找到偏差发生在哪些任务类型和隐性步骤，才能形成有用而不过度的校准规则。'},apply:'今天选一件事，同时写下“计划分钟”和结束后的“实际分钟”，只观察，不评价。'},
 balance:{icon:'🧭',title:'生活领域与主动不均衡',chapter:'book-ch-15',short:'生活不需要七个领域永远平均；更重要的是当前不均衡是不是自己的主动选择。',principle:'考试期、育儿期、冲刺期、恢复期本来就会不均衡。风险在于临时偏重悄悄变成长期默认，并挤掉自己真正想守住的领域。',misconceptions:['误区：工作、家庭、健康、兴趣必须永远均衡。','误区：任何领域减少都意味着失败。主动暂时放下是合法策略。','误区：效率提高就能解决所有冲突。很多冲突本质是资源有限，需要做取舍。'],steps:['明确这阶段想推进、守住、保持和暂时放下什么','给重要但不主攻的领域定义最低版本','为阶段设置重新判断日期','复盘时问“这是我主动选择的吗？”'],tree:[['某领域短期占很多','确认是否有明确阶段终点。'],['重要领域长期消失','先恢复最低版本，不必立刻大幅补偿。'],['想同时推进很多领域','减少主攻数量，其余改为守住/保持。'],['对所有领域都不满意','先选一个最影响整体资源的瓶颈。'],['当前状态很好','也不必把所有领域同时升级。']],cases:{student:'考试月学习偏重是合理的，但要给睡眠和基本活动设最低版本。',work:'项目冲刺两周可以偏工作，但结束日要重新判断而不是无限延长。',care:'育儿阶段个人时间减少是现实，但仍可守住很小的个人空间。',free:'多个项目都想增长 → 只选1–2个主攻，其余进入保持。',slow:'退休后不必把“生产力”继续当核心，可把关系、兴趣和身体放到更高优先级。'},quiz:{q:'“生活领域平衡”更合理的理解是？',options:['所有领域每天投入一样多','所有领域都达到高分','当前不均衡是否与自己的阶段选择一致','永远把工作和家庭各占50%'],correct:2,explain:'生活阶段天然会不均衡，关键是这种不均衡是否被主动选择、是否有最低保护和重新判断机制。'},apply:'写下这阶段一个“想推进”的领域和一个“只需要守住最低版本”的领域。'}
};

function profile(){return Object.assign({guide:'options',contexts:[],envs:[],need:'',onboarded:false},jread(PROFILE_KEY,{}));}
function core(){return Object.assign({entries:[]},jread(CORE_KEY,{}));}
function safeStoreText(){const out=[];try{for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i)||'';if(!/^my_os_/i.test(k)||/app_shell/i.test(k)||k===STATE_KEY)continue;const v=localStorage.getItem(k)||'';if(v.length<120000)out.push(k+' '+v)}}catch(e){}return out.join(' ')}
function recent(){const es=(core().entries||[]).slice().sort((a,b)=>String(a.date).localeCompare(String(b.date))).slice(-14);const txt=es.map(e=>[e.anchor,e.review,e.adjust,e.taskType,e.recovery,e.sceneTags].filter(Boolean).join(' ')).join(' ');const avg=k=>es.length?es.reduce((s,e)=>s+(+e[k]||0),0)/es.length:0;const ratios=es.filter(e=>+e.plannedMinutes>0&&+e.actualMinutes>0).map(e=>+e.actualMinutes/+e.plannedMinutes);return {es,txt,energy:avg('energy'),focus:avg('focus'),stress:avg('stress'),ratio:ratios.length?ratios.reduce((a,b)=>a+b,0)/ratios.length:0}}
function contextText(){const p=profile(),r=recent();return [p.need,(p.contexts||[]).join(' '),(p.envs||[]).join(' '),p.note||'',r.txt,safeStoreText()].join(' ').toLowerCase()}
function unique(a){return [...new Set(a.filter(Boolean))]}
function problemTopics(){const t=contextText(),r=recent(),ids=[];if(/拖延|开始|启动|不想做|procrast|start/.test(t))ids.push('activation');if(/乱|太多|计划|打断|临时|会议|interrupt|plan/.test(t))ids.push('planning');if(/累|疲|恢复|睡眠|压力|stress|recover/.test(t)||r.energy&&r.energy<2.8||r.stress>3.5)ids.push('recovery');if(/没动力|三分钟|动力|坚持|motivat/.test(t))ids.push('motivation');if(/打断|照护|孩子|家庭|care|interrupt/.test(t))ids.push('interruption');if(/考试|学习|课程|study|exam/.test(t))ids.push('learning');if(/倒班|出差|作息不固定|不规律|shift|travel|irregular/.test(t))ids.push('irregular');if(r.ratio>1.25||/估时|超时|时间不够/.test(t))ids.push('estimation');if(/生活领域|家庭|个人空间|平衡|balance/.test(t))ids.push('balance');return unique(ids).slice(0,4)}
function contextTopics(){const p=profile(),c=(p.contexts||[]),e=(p.envs||[]),ids=[];if(c.includes('study'))ids.push('learning','activation');if(c.includes('care')||c.includes('family'))ids.push('interruption','balance');if(c.includes('freelance')||c.includes('create'))ids.push('motivation','planning');if(c.includes('shift')||c.includes('travel')||c.includes('irregular'))ids.push('irregular','recovery');if(c.includes('work'))ids.push('planning','interruption');if(c.includes('retired')||c.includes('health'))ids.push('recovery','balance');if(e.includes('commute')||e.includes('travel'))ids.push('irregular');return unique(ids).slice(0,4)}
function stageTopics(){const t=safeStoreText().toLowerCase(),ids=[];if(/exam|考试|study|学习/.test(t))ids.push('learning','activation');if(/sprint|冲刺|工作/.test(t))ids.push('planning','recovery');if(/recover|恢复/.test(t))ids.push('recovery','balance');if(/care|家庭|照护/.test(t))ids.push('interruption','balance');if(/travel|出差/.test(t))ids.push('irregular','recovery');if(/habit|习惯|兴趣|创作/.test(t))ids.push('motivation','activation');return unique(ids).slice(0,4)}
function strategyTopics(){const t=safeStoreText().toLowerCase(),ids=[];if(/估时|planned|actual|倍率|buffer/.test(t))ids.push('estimation');if(/打断|resume|中断/.test(t))ids.push('interruption');if(/精力|energy|低精力/.test(t))ids.push('recovery');if(/启动|拖延|activation/.test(t))ids.push('activation');if(/计划|弹性|trigger/.test(t))ids.push('planning','irregular');return unique(ids).slice(0,4)}
function experimentTopics(){const t=safeStoreText().toLowerCase(),ids=[];if(/experiment|实验|a\/b|25分钟|45分钟/.test(t))ids.push('planning','estimation');if(/打断|interrupt/.test(t))ids.push('interruption');if(/精力|energy/.test(t))ids.push('recovery');if(/启动|start/.test(t))ids.push('activation');return unique(ids).slice(0,3)}
function buildRoute(){const learned=state().learned||{},basics=['activation','planning','recovery','motivation'],unseen=basics.filter(id=>!learned[id]);return [{id:'basic',n:'1',title:'基础必学',why:'先建立所有人都能用的底层框架。',topics:(unseen.length?unseen:basics).slice(0,4)},{id:'problem',n:'2',title:'当前问题',why:'从你最近实际遇到的问题进入知识。',topics:problemTopics()},{id:'context',n:'3',title:'身份 / 环境',why:'身份只改变优先顺序，不替你决定方法。',topics:contextTopics()},{id:'stage',n:'4',title:'当前生活阶段',why:'考试、冲刺、照护、出差、恢复等阶段需要不同结构。',topics:stageTopics()},{id:'strategy',n:'5',title:'个人规律',why:'用知识解释已经观察到的个人规律，而不是把规律当人格标签。',topics:strategyTopics()},{id:'experiment',n:'6',title:'实验结果',why:'用知识理解小实验为什么可能有效，以及何时不适用。',topics:experimentTopics()}]}
function nextTopic(){const st=state(),route=buildRoute();for(const layer of route){for(const id of layer.topics)if(!st.learned?.[id])return id}const due=Object.entries(st.learned||{}).filter(([id,v])=>v.nextReview&&v.nextReview<=now()).sort((a,b)=>a[1].nextReview-b[1].nextReview);return due[0]?.[0]||problemTopics()[0]||'activation'}
function stats(){const st=state(),learned=Object.keys(st.learned||{}).length,due=Object.values(st.learned||{}).filter(v=>v.nextReview&&v.nextReview<=now()).length,applied=Object.values(st.applied||{}).reduce((s,n)=>s+(+n||0),0);return {learned,due,applied}}
function toastMsg(msg){if(typeof toast==='function')toast(msg);else console.log('[V22]',msg)}

function installHub(){const book=q('#page-book'),head=book?.querySelector('.page-head');if(!book||!head||q('#v22LearningHub'))return false;const h=head.querySelector('h1'),p=head.querySelector('p'),k=head.querySelector('.kicker');if(k)k.textContent='KNOWLEDGE · 教材 × 案例 × 实践';if(h)h.textContent='知识学习 · 个人教材';if(p)p.textContent='先理解，再应用，再用自己的生活证据修正方法。个性化只改变学习顺序，不限制完整知识库。';const hub=document.createElement('section');hub.id='v22LearningHub';hub.className='v22-hub';hub.innerHTML=`<div id="v22Guide"></div><div class="v22-toolbar"><div><div class="kicker">V22 · PERSONAL LEARNING</div><h2>今天最值得学什么？</h2><p class="muted">不用从第一章顺序读。系统会从基础、当前问题、环境、阶段、个人规律和实验结果六个层次给你导航。</p></div><button class="btn primary" id="v22NextBtn">开始下一篇</button></div><div class="v22-stats" id="v22Stats"></div><div class="v22-tabs"><button data-v22tab="route" class="active">我的学习路径</button><button data-v22tab="cases">同题不同人</button><button data-v22tab="trees">决策树</button><button data-v22tab="review">复习卡</button></div><div id="v22Panel"></div>`;head.insertAdjacentElement('afterend',hub);hub.addEventListener('click',handleHubClick);renderHub();return true}
function renderGuide(){const el=q('#v22Guide');if(!el)return;if(sget(GUIDE_KEY)==='1'){el.innerHTML='';return}el.innerHTML=`<div class="v22-guide"><div><b>知识区怎么用？只需要这 4 步</b><p>① 看系统推荐的一篇 → ② 看不同人的现实案例 → ③ 做一个不计分的理解检查 → ④ 选一个动作放进今天。以后需要时再用复习卡回来。</p></div><button class="btn ghost" id="v22GuideDone">知道了</button></div>`}
function renderStats(){const el=q('#v22Stats');if(!el)return;const x=stats();el.innerHTML=`<div><b>${x.learned}</b><small>已学主题</small></div><div><b>${x.due}</b><small>待复习</small></div><div><b>${x.applied}</b><small>已应用到生活</small></div><div><b>${Object.keys(TOPICS).length}</b><small>核心实践主题</small></div>`}
function topicCard(id,reason=''){const t=TOPICS[id];if(!t)return'';const st=state(),l=st.learned?.[id];return `<button class="v22-topic-card" data-open-topic="${id}"><span class="v22-topic-icon">${t.icon}</span><span><b>${esc(t.title)}</b><small>${esc(reason||t.short)}</small>${l?'<em>已学 · 可复习</em>':''}</span></button>`}
function renderRoute(){const route=buildRoute();return `<div class="v22-route">${route.map(layer=>`<div class="v22-layer ${layer.topics.length?'':'empty'}"><div class="v22-layer-head"><span>${layer.n}</span><div><b>${layer.title}</b><small>${layer.why}</small></div></div><div class="v22-layer-topics">${layer.topics.length?layer.topics.map(id=>topicCard(id)).join(''):'<div class="v22-empty">现在没有足够信息需要在这一层强行推荐。继续正常使用即可。</div>'}</div></div>`).join('')}</div>`}
function renderCases(){const ids=unique(['activation','planning','recovery','learning','interruption','motivation',...problemTopics()]).slice(0,8);return `<div class="v22-section-intro"><b>同一个问题，不同生活环境怎么做？</b><p>下面是基于常见现实场景整理的<strong>合成情境案例</strong>，用于比较方法如何随环境变化，不代表对某类人的固定判断。</p></div><div class="v22-case-grid">${ids.map(id=>{const t=TOPICS[id];return `<article class="v22-case-topic"><div class="v22-case-title">${t.icon}<b>${t.title}</b><button data-open-topic="${id}">完整学习</button></div>${PERSONAS.map(p=>`<div class="v22-case-line"><span>${p.icon} ${p.name}</span><p>${esc(t.cases[p.id])}</p></div>`).join('')}</article>`}).join('')}</div>`}
function renderTrees(){const ids=unique([...problemTopics(),'activation','planning','recovery','interruption','estimation']).slice(0,7);return `<div class="v22-section-intro"><b>先判断问题，再选方法</b><p>决策树不是诊断工具，只帮助把“我做不到”拆成更具体、可行动的问题。</p></div><div class="v22-tree-list">${ids.map(id=>{const t=TOPICS[id];return `<article class="v22-tree-card"><header>${t.icon}<b>${t.title}</b><button data-open-topic="${id}">展开学习</button></header>${t.tree.slice(0,4).map(([a,b])=>`<div><span>如果：${esc(a)}</span><p>→ ${esc(b)}</p></div>`).join('')}</article>`}).join('')}</div>`}
function renderReview(){const st=state(),entries=Object.entries(st.learned||{}).sort((a,b)=>(a[1].nextReview||0)-(b[1].nextReview||0));if(!entries.length)return `<div class="v22-review-empty"><b>还没有复习卡</b><p>学完任一核心主题后会自动建立复习卡。这里没有连续打卡，也不会因为晚几天复习而判定失败。</p><button class="btn primary" data-open-topic="${nextTopic()}">先学下一篇</button></div>`;return `<div class="v22-review-list">${entries.map(([id,v])=>{const t=TOPICS[id];if(!t)return'';const due=!v.nextReview||v.nextReview<=now();const days=v.nextReview?Math.ceil((v.nextReview-now())/DAY):0;return `<article class="v22-review-card ${due?'due':''}"><div><span>${t.icon}</span><div><b>${t.title}</b><small>${due?'现在可以复习':`约 ${days} 天后再看`}</small></div></div><p>${t.short}</p><div class="v22-review-actions"><button data-open-topic="${id}">打开知识卡</button><button data-review="${id}" data-review-result="clear">我还记得</button><button data-review="${id}" data-review-result="foggy">有点模糊</button></div></article>`}).join('')}</div>`}
function renderHub(){renderGuide();renderStats();const st=state(),tab=st.tab||'route';qa('#v22LearningHub [data-v22tab]').forEach(b=>b.classList.toggle('active',b.dataset.v22tab===tab));const p=q('#v22Panel');if(!p)return;p.innerHTML=tab==='cases'?renderCases():tab==='trees'?renderTrees():tab==='review'?renderReview():renderRoute();const n=TOPICS[nextTopic()],btn=q('#v22NextBtn');if(btn&&n)btn.textContent=`下一篇：${n.title}`}
function handleHubClick(e){const tab=e.target.closest('[data-v22tab]');if(tab){const st=state();st.tab=tab.dataset.v22tab;save(st);renderHub();return}const op=e.target.closest('[data-open-topic]');if(op){openTopic(op.dataset.openTopic);return}if(e.target.closest('#v22NextBtn')){openTopic(nextTopic());return}if(e.target.closest('#v22GuideDone')){sset(GUIDE_KEY,'1');renderGuide();return}const rv=e.target.closest('[data-review]');if(rv){reviewTopic(rv.dataset.review,rv.dataset.reviewResult);return}}
function ensureModal(){let m=q('#v22StudyModal');if(m)return m;m=document.createElement('div');m.id='v22StudyModal';m.className='v22-modal';m.innerHTML=`<div class="v22-modal-card"><button class="v22-modal-close" id="v22ModalClose">×</button><div id="v22ModalBody"></div></div>`;document.body.appendChild(m);m.addEventListener('click',e=>{if(e.target===m||e.target.closest('#v22ModalClose'))closeModal();const b=e.target.closest('[data-v22-quiz]');if(b)answerQuiz(b.dataset.v22Quiz,+b.dataset.opt);const a=e.target.closest('[data-apply-topic]');if(a)applyTopic(a.dataset.applyTopic);const l=e.target.closest('[data-learn-topic]');if(l)markLearned(l.dataset.learnTopic);const d=e.target.closest('[data-deep-chapter]');if(d)deepRead(d.dataset.deepChapter)});return m}
function openTopic(id){const t=TOPICS[id];if(!t)return;const st=state(),l=st.learned?.[id],m=ensureModal(),body=q('#v22ModalBody');body.innerHTML=`<div class="v22-study-head"><span>${t.icon}</span><div><div class="kicker">CORE KNOWLEDGE · ${l?'复习':'学习'}</div><h2>${t.title}</h2><p>${t.short}</p></div></div><section class="v22-knowledge-card"><h3>先记住这一句话</h3><p>${t.principle}</p></section><section><h3>常见误区</h3><div class="v22-misconceptions">${t.misconceptions.map(x=>`<div>⚠️ ${esc(x)}</div>`).join('')}</div></section><section><h3>可以怎么做</h3><div class="v22-step-list">${t.steps.map((x,i)=>`<div><span>${i+1}</span><p>${esc(x)}</p></div>`).join('')}</div></section><section><h3>同一个问题，不同人怎么调整</h3><div class="v22-persona-tabs">${PERSONAS.map(p=>`<details><summary>${p.icon} ${p.name}</summary><p>${esc(t.cases[p.id])}</p></details>`).join('')}</div></section><section><h3>快速决策树</h3><div class="v22-tree-inline">${t.tree.map(([a,b])=>`<div><b>如果：${esc(a)}</b><p>→ ${esc(b)}</p></div>`).join('')}</div></section><section class="v22-quiz" data-quiz-box="${id}"><h3>理解检查 · 不计分</h3><p>${esc(t.quiz.q)}</p><div>${t.quiz.options.map((o,i)=>`<button data-v22-quiz="${id}" data-opt="${i}">${String.fromCharCode(65+i)}. ${esc(o)}</button>`).join('')}</div><p class="v22-quiz-explain" id="v22QuizExplain"></p></section><section class="v22-apply"><h3>学完立即应用</h3><p>${esc(t.apply)}</p><div><button class="btn primary" data-apply-topic="${id}">应用到今天</button><button class="btn ghost" data-learn-topic="${id}">${l?'再记一次':'标记为已学'}</button><button class="btn ghost" data-deep-chapter="${t.chapter}">深入原教材章节</button></div></section><p class="v22-evidence-note">提示：这里提供的是通用知识和常见情境。真正属于“你的方法”的结论，仍应由你的真实记录、个人实验和你的确认共同决定。</p>`;m.classList.add('show');document.body.classList.add('v22-modal-open');const st2=state();st2.history=(st2.history||[]).slice(-99);st2.history.push({id,at:now(),type:'open'});save(st2)}
function closeModal(){q('#v22StudyModal')?.classList.remove('show');document.body.classList.remove('v22-modal-open')}
function answerQuiz(id,opt){const t=TOPICS[id];if(!t)return;const ok=opt===t.quiz.correct,box=q(`[data-quiz-box="${id}"]`),ex=box?.querySelector('.v22-quiz-explain');if(ex){ex.className='v22-quiz-explain show '+(ok?'ok':'learn');ex.innerHTML=`<b>${ok?'方向对了':'这里最容易混淆'}</b> · ${esc(t.quiz.explain)}`}const st=state();st.quiz[id]={at:now(),last:opt,understood:ok};save(st)}
function markLearned(id){if(!TOPICS[id])return;const st=state(),old=st.learned?.[id]||{},level=Math.min(4,(old.level||0)+1),days=[1,3,7,14,30][level]||30;st.learned[id]={firstAt:old.firstAt||now(),lastAt:now(),level,nextReview:now()+days*DAY};st.history=(st.history||[]).slice(-99);st.history.push({id,at:now(),type:'learned'});save(st);renderHub();toastMsg('已加入你的学习与复习路径');const btn=q(`[data-learn-topic="${id}"]`);if(btn)btn.textContent='已记录 · 以后再复习'}
function reviewTopic(id,result){const st=state(),old=st.learned?.[id]||{firstAt:now(),level:0};let level=result==='foggy'?0:Math.min(4,(old.level||0)+1);const days=[1,3,7,14,30][level]||30;st.learned[id]={...old,lastAt:now(),level,nextReview:now()+days*DAY};save(st);renderHub();toastMsg(result==='foggy'?'已安排更早复习，不代表退步':'已把下一次复习间隔拉长')}
function applyTopic(id){const t=TOPICS[id];if(!t)return;const st=state();st.applied[id]=(st.applied[id]||0)+1;st.history=(st.history||[]).slice(-99);st.history.push({id,at:now(),type:'apply'});save(st);closeModal();try{if(typeof go==='function')go('today')}catch(e){}setTimeout(()=>{const adjust=q('#adjust'),anchor=q('#anchor'),review=q('#review');const text=`今天尝试：${t.apply}`;if(adjust){adjust.value=(adjust.value.trim()?adjust.value.trim()+'\n':'')+text;adjust.dispatchEvent(new Event('input',{bubbles:true}))}else if(anchor&&!anchor.value.trim()){anchor.value=t.apply;anchor.dispatchEvent(new Event('input',{bubbles:true}))}else if(review){review.value=(review.value.trim()?review.value.trim()+'\n':'')+text;review.dispatchEvent(new Event('input',{bubbles:true}))}toastMsg('已经放进今天。做不做、做多少仍由你决定。');renderHub()},180)}
function deepRead(chapter){closeModal();try{if(typeof go==='function')go('book')}catch(e){}setTimeout(()=>{const el=document.getElementById(chapter);if(el){el.scrollIntoView({behavior:'smooth',block:'start'});el.classList.add('v22-chapter-pulse');setTimeout(()=>el.classList.remove('v22-chapter-pulse'),1800)}else toastMsg('完整教材中保留了对应主题，可使用章节搜索继续深入。')},180)}
function installDashboardCard(){const dash=q('#page-dashboard'),head=dash?.querySelector('.page-head');if(!dash||!head||q('#v22DashLearn'))return;const id=nextTopic(),t=TOPICS[id];if(!t)return;const card=document.createElement('div');card.id='v22DashLearn';card.className='v22-dash-learn';card.innerHTML=`<div><div class="kicker">知识学习 · 下一篇</div><b>${t.icon} ${t.title}</b><p>${t.short}</p></div><button class="btn ghost">现在学</button>`;card.addEventListener('click',()=>{try{if(typeof go==='function')go('book')}catch(e){}setTimeout(()=>openTopic(id),120)});head.insertAdjacentElement('afterend',card)}
function brand(){const small=q('.brand small'),rt=q('#runtimeBadge span');if(small)small.textContent='V22 · Adaptive Life · 知识教材增强';if(rt)rt.textContent='V22 · My OS';if(typeof titles==='object')titles.book='知识学习'}
function boot(){brand();const ok=installHub();installDashboardCard();if(!ok)setTimeout(boot,350)}
boot();setTimeout(()=>{installHub();installDashboardCard();renderHub()},900);
window.myOSV22={openTopic,renderHub,nextTopic,topics:TOPICS};
})();