const app=document.querySelector('#app'), bottom=document.querySelector('#bottom'), fab=document.querySelector('#fab');
const KEY='rfaV7';
const defaults={tab:'home',xp:0,trips:0,discoveries:0,catches:0,shares:0,knowledge:0,map:{structure:false,edge:false,life:false},dex:{},lastResult:'还没有开始第一次现实任务',history:[],checks:Array(12).fill(false),nextMystery:'上次浅区有活动。今天环境变了：它还在原来的位置吗？'};
let save=(()=>{try{return Object.assign({},defaults,JSON.parse(localStorage.getItem(KEY)||'{}'))}catch{return JSON.parse(JSON.stringify(defaults))}})();
save.map=Object.assign({},defaults.map,save.map||{});save.dex=save.dex||{};save.history=save.history||[];save.checks=Array.isArray(save.checks)?save.checks:Array(12).fill(false);
let S={tab:save.tab||'home',screen:'root',mode:null,missionType:'structure',event:null,zeroValidity:null,bet:null,wager:null,challenge:null,clue:null,stream:null,scanId:'structure',tripActive:false,tripEvents:[],learnTab:'path',decisionFault:'none',planner:{spot:'pond',target:'crucian',water:'calm',goal:'bite'},img:null,shootStyle:'hero',fish:'翘嘴',size:'',weight:'',place:'隐藏地点',story:'',captionStyle:'brag',caption:'',cardBlob:null,photoCatchLogged:false};
const navs=[['home','🏠','首页'],['play','🎯','开钓'],['decision','🧭','决策'],['learn','📚','知识'],['me','👤','我的']];
const xpTitle=x=>x<40?'见习探钓员':x<100?'水边观察员':x<200?'证据猎手':x<350?'独立判断者':'水域侦探';
function persist(){save.tab=S.tab;localStorage.setItem(KEY,JSON.stringify(save))}
function gainXP(n,why){save.xp+=n;if(why)addHistory(`+${n} XP · ${why}`);persist()}
function addHistory(text){save.history.unshift({t:new Date().toLocaleString([], {month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'}),text});save.history=save.history.slice(0,12);persist()}
function stopCam(){if(S.stream){S.stream.getTracks().forEach(t=>t.stop());S.stream=null}}
function tone(f=620,d=.06){try{const A=tone.a||(tone.a=new(window.AudioContext||window.webkitAudioContext)()),o=A.createOscillator(),g=A.createGain();o.frequency.value=f;g.gain.setValueAtTime(.018,A.currentTime);g.gain.exponentialRampToValueAtTime(.001,A.currentTime+d);o.connect(g).connect(A.destination);o.start();o.stop(A.currentTime+d)}catch{}}
function shell(body,title='Reality Fishing Adventure'){app.innerHTML=`<div class="top"><div class="brand"><div class="brandmark">🐟</div><div><b>${title}</b><small>${xpTitle(save.xp)} · ${save.xp} XP</small></div></div><button id="reset" class="ghost">重置演示</button></div>${body}<div class="tiny">V7 综合原型：把实战知识、现实任务、判断游戏、镜头侦察、鱼获分享与个人成长放到同一套产品里。镜头侦察不声称能看见水下鱼；AI识图/真实空间AR尚未接服务端或原生AR能力。</div>`;const r=document.querySelector('#reset');if(r)r.onclick=()=>{if(confirm('清空V7本机演示数据？')){localStorage.removeItem(KEY);location.reload()}};nav()}
function nav(){bottom.innerHTML=`<div class="inner">${navs.map(([id,ic,t])=>`<button class="nav ${S.tab===id?'on':''}" data-nav="${id}"><span>${ic}</span>${t}</button>`).join('')}</div>`;bottom.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>{stopCam();S.tab=b.dataset.nav;S.screen='root';S.mode=null;save.tab=S.tab;persist();render()})}
fab.onclick=()=>{stopCam();S.photoCatchLogged=false;S.screen='photo';S.mode='photo';renderPhoto()};
function home(){const p=Math.min(100,save.xp/3.5);shell(`<div class="hero"><span class="eyebrow">今天想怎么钓？</span><h1>知识、判断、实战、记录，<br>都在这里。</h1><div class="lead">不要求按固定流程。出发前查准备；到水边拿任务或做判断；没口就排错；上鱼后拍帅、记录、分享。</div></div><section class="card deep"><div class="title">今天最推荐：先拿一个现实任务</div><div class="sub">30 秒内告诉你先看哪里、先试什么。完成后现实结果会推进你的水域地图。</div><button class="primary gold" data-jump="play">🎯 带我开始</button></section><div class="quick"><button data-jump="decision"><b>🧭 我不知道怎么钓</b><small>30秒生成开钓方案</small></button><button data-photo="1"><b>📸 我上鱼了</b><small>教我拍帅 + 做朋友圈</small></button><button data-jump="learn"><b>📚 我想先学</b><small>8步路线 / 装备 / 读水 / 鱼种</small></button><button data-jump="me"><b>🗺️ 看我的成长</b><small>水域、鱼获、证据、履历</small></button></div><section class="card"><span class="eyebrow">个人进度</span><div class="title">${xpTitle(save.xp)}</div><div class="progress"><i style="width:${p}%"></i></div><div class="pillrow"><span class="pill on">XP ${save.xp}</span><span class="pill ${save.trips?'on':''}">钓行 ${save.trips}</span><span class="pill ${save.discoveries?'on':''}">发现 ${save.discoveries}</span><span class="pill ${save.catches?'on':''}">鱼获 ${save.catches}</span></div><div class="sub" style="margin-top:10px">最近：${save.lastResult}</div></section>`);app.querySelectorAll('[data-jump]').forEach(b=>b.onclick=()=>{S.tab=b.dataset.jump;S.screen='root';render()});app.querySelector('[data-photo]')?.addEventListener('click',()=>{S.photoCatchLogged=false;S.screen='photo';S.mode='photo';renderPhoto()})}
