const captionToneLabels={brag:'高调',fun:'搞笑',pro:'专业',low:'低调',story:'故事',poetic:'氛围',angler:'钓鱼佬',short:'极简'};
const captionOpen={
 brag:['今天这条必须占一次朋友圈。','今天不是来凑数的。','水边吹了半天风，终于轮到我说话。','这次不解释，先上鱼。','钓鱼佬今天申请高调五分钟。','本来想低调，鱼不同意。','今天的主角已经自己游进镜头了。'],
 fun:['本来都准备写空军总结了。','蚊子还没喂饱，鱼先投降了。','今天最大的失误，是嘴角没压住。','说好随便钓钓，结果事情有点大。','鱼：我只是路过。 我：来都来了。','今天终于不用研究空军的文学表达了。','钓鱼人的快乐，有时候就这么突然。'],
 pro:['今日实钓记录。','本次钓行留档。','现场条件与鱼获记录如下。','一次可复盘的真实鱼获。','今天把判断变成了一个有效样本。','实钓结果更新个人水域模型。','今天这条鱼，重点不只是鱼本身。'],
 low:['风景不错，运气也刚好不错。','今天水边坐得挺值。','留个小记录。','不多说，记住今天就好。','天气、流水、鱼，一切刚刚好。','安静钓鱼，顺便收获一点快乐。','今天有鱼，挺好。'],
 story:['故事从“再试最后几竿”开始。','今天前半场并不顺利。','这条鱼前面，已经铺垫了很久。','有些鱼获，照片只有一秒，过程却很长。','从没口到有口，中间只改了一件事。','今天的转折发生在我准备放弃的时候。','这一条值得把过程也记下来。'],
 poetic:['风从水面过，鱼从故事里来。','夕阳、鱼鳞和一点刚好的运气。','水面安静的时候，惊喜反而更清楚。','今天的光线，刚好替鱼鳞加了滤镜。','把一段水边时间，装进一张照片。','风景负责铺垫，鱼负责收尾。','今天的水面给了一个漂亮答案。'],
 angler:['钓鱼佬日报：今天有东西可以吹。','群里潜水半天，现在轮到我发图。','装备没白背，早起没白起。','今天可以理直气壮地说：有口。','这条够不够换一晚吹牛资格？','各位钓友，今日素材已到账。','空军群暂时把我移出群聊。'],
 short:['上岸。','破局。','今天有鱼。','收工照。','记一条。','值了。','水边见。']
};
const captionCatch=['主角是{fish}{stat}。','{fish}{stat}，真实上岸。','今天的答案：{fish}{stat}。','镜头里这一条是{fish}{stat}。','这一竿带回来一条{fish}{stat}。','鱼获确认：{fish}{stat}。','终于等到这条{fish}{stat}。','今天水里给我的回信，是{fish}{stat}。'];
const captionBridge=['地点先保密，故事可以公开。','鱼情不会每次复制，但今天值得记住。','一次鱼获不代表规律，下次还会继续验证。','这一刻先享受，规律留给下一次复盘。','结果只是结尾，前面的判断才最有意思。','今天的线索，留着下次继续用。'];
const captionEnd={
 brag:['今天允许我嚣张到睡觉。','鱼情可以不给面子，照片必须给。','朋友圈库存终于补货。','钓鱼佬的快乐就是这么朴素。','这张先发，细节晚上慢慢吹。','下一条可以晚点来，今天已经够了。','先让它在朋友圈游一圈。'],
 fun:['嘴角比鱼竿还难压。','今晚终于不用P一条鱼上去了。','请忽略我假装淡定的表情。','鱼已经放回去了，牛准备吹一年。','照片保存成功，空军记忆自动删除。','今天蚊子和我都吃上了。','下次还敢不敢来不知道，今天先笑。'],
 pro:['后续继续对相似条件做重复验证。','保留这一条作为个人水域样本。','下一次重点验证相同结构是否可复制。','记录比单次结论更重要。','下次会继续控制变量观察。','先记录事实，再讨论规律。','这次作为有效样本归档。'],
 low:['留个纪念，下次再见。','够开心就好。','水边的一天，收好。','不必很大，刚好喜欢。','今天就这样，很满足。','下次继续。','简单记录一下。'],
 story:['所以最后这一张，不只是鱼获照。','这就是今天故事的结尾。','前面的等待，在这一刻都有了解释。','下次再来，看看这个判断还能不能成立。','鱼获会忘，过程最好别忘。','水边没有白坐，每次都有一点新答案。','今天这一章，到这里刚好。'],
 poetic:['水面归于安静，照片留下来了。','把晚风和鱼鳞一起存档。','下一次水边，再续这一页。','鱼回到水里，光留在照片里。','这一刻，刚好值得记住。','风景会散，记忆先保存。','今天的水面，收进相册。'],
 angler:['今晚群聊发言权+1。','懂的都懂，先不报点。','位置别问，问就是本地水域。','鱼已回水，照片留下继续吹。','明天谁空军谁请水。','装备党今天终于有交代。','各位钓友，评论区开始估重。'],
 short:['🎣','就这样。','下一竿见。','收。','值得。','继续。','😎']
};
const captionDecor=['#今日鱼获 #钓鱼日常','#钓鱼佬的快乐','#真实鱼获 #水边生活','#今天不空军','#钓鱼人的周末','#鱼获记录'];
function captionCombinationCount(){return Object.keys(captionOpen).reduce((n,k)=>n+captionOpen[k].length*captionCatch.length*captionBridge.length*captionEnd[k].length*captionDecor.length,0)}
function pick(a){return a[Math.floor(Math.random()*a.length)]}
function renderPhoto(){if(S.screen==='photoConfirm')return photoConfirm();if(S.screen==='photoCaption')return photoCaption();if(S.screen==='photoCard')return photoCard();shell(`<div class="hero"><span class="eyebrow">拍照晒鱼</span><h1>先拍帅，再让系统帮你讲故事。</h1><div class="lead">先看姿势建议再拍；拍完觉得角度、手势或背景不满意，可以直接重新拍，不必退出流程。</div></div><section class="card gold"><div class="title">先选拍摄风格</div><div class="shootstyles">${[['hero','🏆 巨物英雄照','鱼靠近镜头，人物稍后，制造体积感'],['low','🌊 低机位水边','摄影者蹲低，让鱼和水面更有冲击'],['sunset','🌅 夕阳氛围','侧逆光，保住天空和鱼身层次'],['gear','🎣 装备故事照','鱼 + 竿轮 + 水面一起讲故事']].map(([id,t,s])=>`<button class="shoot ${S.shootStyle===id?'on':''}" data-shoot="${id}"><b>${t}</b><small>${s}</small></button>`).join('')}</div></section><section class="card green"><div class="title">${shootTip().title}</div><div class="sub">${shootTip().body}</div><div class="pillrow"><span class="pill on">鱼眼清楚</span><span class="pill on">别遮鱼身</span><span class="pill on">背景简洁</span><span class="pill on">手臂稍弯</span></div><label class="upload">📸 按这个姿势拍 / 从相册选<input id="photoInput" type="file" accept="image/*" capture="environment"></label><button id="photoClose" class="secondary" style="width:100%;margin-top:9px">返回刚才页面</button></section>`,'拍照晒鱼');app.querySelectorAll('[data-shoot]').forEach(b=>b.onclick=()=>{S.shootStyle=b.dataset.shoot;renderPhoto()});document.querySelector('#photoInput').onchange=e=>loadPhoto(e.target.files[0]);document.querySelector('#photoClose').onclick=()=>{S.screen='root';S.mode=null;render()}}
function shootTip(){return{hero:{title:'鱼向镜头送一点，但别把手臂完全伸直。',body:'人物后半步，鱼头略高于鱼尾；优先1×主摄，别用超广角贴脸。'},low:{title:'摄影的人蹲低一点，鱼保持水平。',body:'让水面进入背景上半部，避开地面杂物；人物略侧身通常比正对镜头更有力量。'},sunset:{title:'别让脸和鱼完全黑掉，鱼身转向侧光。',body:'太阳放在人物侧后方，点击鱼身测光；宁可天空稍亮，也要保住鱼鳞细节。'},gear:{title:'装备进画面，但只能当配角。',body:'鱼占画面约一半，竿轮斜着形成引导线；饵、抄网等只留1—2件。'}}[S.shootStyle]}
function loadPhoto(file){if(!file)return;let r=new FileReader();r.onload=()=>{S.img=r.result;S.cardBlob=null;S.screen='photoConfirm';renderPhoto()};r.readAsDataURL(file)}
function retakeControl(){return `<label class="retake">🔁 重新拍 / 换一张<input class="retakeInput" type="file" accept="image/*" capture="environment"></label>`}
function bindRetake(){document.querySelectorAll('.retakeInput').forEach(x=>x.onchange=e=>loadPhoto(e.target.files[0]))}
function photoConfirm(){shell(`<section class="card green"><div class="frame"><img src="${S.img}"><div class="guideoverlay"></div></div><div class="title">先看一眼：这张够帅吗？</div><div class="sub">检查鱼眼是否清楚、鱼身有没有被手遮住、背景是否杂乱、鱼是否歪斜。觉得不对就马上重拍。</div>${retakeControl()}<button id="backTips" class="secondary" style="width:100%;margin:8px 0 12px">← 回拍摄建议重新选风格</button><div class="row"><div class="fieldinput"><label>鱼种</label><select id="fish"><option>翘嘴</option><option>鲫鱼</option><option>鲤鱼</option><option>黑鱼</option><option>鲈鱼</option><option>鳜鱼</option><option>黄颡鱼</option><option>其他</option></select></div><div class="fieldinput"><label>地点公开</label><select id="place"><option>隐藏地点</option><option>只显示城市</option><option>本地水域</option></select></div></div><div class="row"><div class="fieldinput"><label>长度（可空）</label><input id="size" placeholder="58 cm" value="${escPhoto(S.size)}"></div><div class="fieldinput"><label>重量（可空）</label><input id="weight" placeholder="2.3 kg" value="${escPhoto(S.weight)}"></div></div><div class="fieldinput" style="margin-top:9px"><label>一句故事（可空）</label><input id="story" placeholder="空军两小时，换边界后破局" value="${escPhoto(S.story)}"></div><button id="capNext" class="primary">生成朋友圈文案</button></section>`,'拍照晒鱼');document.querySelector('#fish').value=S.fish;document.querySelector('#place').value=S.place||'隐藏地点';bindRetake();document.querySelector('#backTips').onclick=()=>{S.screen='photo';renderPhoto()};document.querySelector('#capNext').onclick=()=>{S.fish=document.querySelector('#fish').value;S.place=document.querySelector('#place').value;S.size=document.querySelector('#size').value.trim();S.weight=document.querySelector('#weight').value.trim();S.story=document.querySelector('#story').value.trim();makeCaption();S.screen='photoCaption';renderPhoto()}}
function escPhoto(s){return String(s||'').replace(/&/g,'&amp;').replace(/"/g,'&quot;').replace(/</g,'&lt;')}
function makeCaption(){let style=captionOpen[S.captionStyle]?S.captionStyle:'brag',stat=[S.size,S.weight].filter(Boolean).join(' · '),vals={fish:S.fish,stat:stat?'，'+stat:''};let fill=t=>t.replaceAll('{fish}',vals.fish).replaceAll('{stat}',vals.stat),story=S.story?S.story.replace(/[。.!！]+$/,'')+'。':pick(captionBridge),place=(S.place&&S.place!=='隐藏地点')?`\n地点：${S.place}。`:'';let next='';for(let tries=0;tries<12;tries++){let parts=[pick(captionOpen[style]),fill(pick(captionCatch)),story,pick(captionEnd[style]),pick(captionDecor)];next=parts.slice(0,2).join('\n')+place+'\n'+parts.slice(2).join('\n');if(next!==S.caption)break}S.caption=next}
function photoCaption(){shell(`<section class="card reward"><span class="eyebrow">朋友圈文案 · 本地随机组合</span><div class="title">今天想怎么炫？</div><div class="sub">不是只有4条模板：8种语气 × 多组句库，基础组合约 ${captionCombinationCount().toLocaleString()} 种，再叠加鱼种、尺寸和你的故事。</div><div class="chips">${Object.entries(captionToneLabels).map(([id,t])=>`<button class="chip ${S.captionStyle===id?'on':''}" data-cap="${id}">${t}</button>`).join('')}</div><div class="caption" style="margin-top:12px">${S.caption}</div><button id="regenCap" class="primary">🎲 换一条，不重复刚才那句</button><button id="makeCard" class="secondary" style="width:100%;margin-top:9px">生成鱼获分享卡</button><button id="copyCap" class="secondary" style="width:100%;margin-top:9px">复制文案</button>${retakeControl()}</section>`,'拍照晒鱼');app.querySelectorAll('[data-cap]').forEach(b=>b.onclick=()=>{S.captionStyle=b.dataset.cap;makeCaption();renderPhoto()});document.querySelector('#regenCap').onclick=()=>{makeCaption();renderPhoto()};document.querySelector('#copyCap').onclick=()=>navigator.clipboard?.writeText(S.caption);document.querySelector('#makeCard').onclick=()=>{S.screen='photoCard';renderPhoto();setTimeout(drawCard,30)};bindRetake()}
function photoCard(){shell(`<section class="card gold"><span class="eyebrow">CATCH STORY CARD</span><canvas id="cv" width="1080" height="1350"></canvas><button id="share" class="primary">分享到朋友圈 / 其他App</button><button id="backCaption" class="secondary" style="width:100%;margin-top:9px">← 换文案</button>${retakeControl()}<button id="donePhoto" class="secondary" style="width:100%;margin-top:9px">完成</button></section>`,'拍照晒鱼');document.querySelector('#share').onclick=shareCard;document.querySelector('#backCaption').onclick=()=>{S.screen='photoCaption';renderPhoto()};document.querySelector('#donePhoto').onclick=()=>{S.screen='root';S.mode=null;S.img=null;render()};bindRetake()}
function drawCard(){let cv=document.querySelector('#cv'),ctx=cv.getContext('2d'),img=new Image();img.onload=()=>{ctx.fillStyle='#073c42';ctx.fillRect(0,0,1080,1350);let sc=Math.max(1080/img.width,880/img.height),w=img.width*sc,h=img.height*sc;ctx.drawImage(img,(1080-w)/2,0,w,h);let g=ctx.createLinearGradient(0,620,0,1350);g.addColorStop(0,'rgba(7,60,66,0)');g.addColorStop(.35,'rgba(7,60,66,.82)');g.addColorStop(1,'rgba(7,60,66,1)');ctx.fillStyle=g;ctx.fillRect(0,600,1080,750);ctx.fillStyle='#ffbd59';ctx.font='700 34px system-ui';ctx.fillText('REAL CATCH',64,920);ctx.fillStyle='#fff';ctx.font='800 72px system-ui';ctx.fillText(S.fish,64,1005);ctx.font='500 34px system-ui';ctx.fillStyle='#d7e7e3';ctx.fillText([S.size,S.weight,S.place].filter(Boolean).join(' · '),64,1065);wrap(ctx,S.caption.replace(/\n/g,' '),64,1140,950,42,2);ctx.font='500 24px system-ui';ctx.fillStyle='#ffbd59';ctx.fillText('Reality Fishing Adventure',64,1300);cv.toBlob(b=>S.cardBlob=b,'image/jpeg',.92)};img.src=S.img}
function wrap(ctx,text,x,y,max,lineH,maxLines){ctx.font='500 30px system-ui';ctx.fillStyle='#eef8f5';let line='',n=0;for(const ch of text){let t=line+ch;if(ctx.measureText(t).width>max){ctx.fillText(line,x,y+n*lineH);n++;line=ch;if(n>=maxLines)return}else line=t}if(n<maxLines)ctx.fillText(line,x,y+n*lineH)}
async function shareCard(){if(!S.photoCatchLogged){if(!save.dex[S.fish])save.dex[S.fish]=0;save.dex[S.fish]++;save.catches++;S.photoCatchLogged=true;}gainXP(15,'完成一张鱼获故事卡');const file=S.cardBlob?new File([S.cardBlob],'catch-story.jpg',{type:'image/jpeg'}):null;try{if(file&&navigator.canShare?.({files:[file]})){await navigator.share({files:[file],text:S.caption,title:'我的鱼获'});save.shares++;gainXP(5,'分享鱼获')}else if(navigator.share){await navigator.share({text:S.caption,title:'我的鱼获'});save.shares++;gainXP(5,'分享鱼获')}else{await navigator.clipboard?.writeText(S.caption);alert('浏览器不支持系统分享，文案已复制。')}}catch(e){if(e?.name!=='AbortError')alert('分享未完成，可复制文案后手动发送。')}persist()}
